### PR TITLE
 feat(Link): add externalIcon prop

### PR DESCRIPTION
**Pull request by sun0day**
## 📝 Description

> Add a brief description

1. add new props `externalIcon` to control `Link` suffix external icon.
2. set `Link` rel="noopener" and target="_blank" when `isExternal=true`

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

image

----

image

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by sun0day** [comment]
Seems like there are some circular dependencies in `apps/docs`

image

**Comment by jrgarciadev** [comment]
Hey @sun0day thanks for contributing, could we change the `Loading` component to a custom link icon?

**Comment by jrgarciadev** [comment]
hey @sun0day what about this one?

link-svg

**Comment by sun0day** [comment]
> hey @sun0day what about this one?
> 
> link-svg

Cool. Done.

image

**Comment by jrgarciadev** [comment]
Hey @sun0day sorry for the delay, could you please fix the issues?

**Comment by sun0day** [comment]
> Hey @sun0day thanks for contributing, could we change the `Loading` component to a custom link icon?



> Hey @sun0day sorry for the delay, could you please fix the issues?

Done

**Comment by jrgarciadev** [comment]
Hey @sun0day thanks for fixing the issues however looks like something is broken in the example code, could you take a look please?

CleanShot 2023-01-06 at 22 26 26

**Comment by sun0day** [comment]
> Hey @sun0day thanks for fixing the issues however looks like something is broken in the example code, could you take a look, please?
> 
> CleanShot 2023-01-06 at 22 26 26

This error seems to be caused by deployment. The preview ui version mismatched the latest code in the branch.

image

**Pull request merged**
