### PR TITLE
components/tooltip replace "useLayoutEffect" with "useSafeLayoutEffect"

### LINKED ISSUE #1954: [BUG] - SSR "useLayoutEffect" in Tooltip component
### NextUI Version

2.2.8

### Describe the bug

There seems to be a similar problem in the latest version as in a previous issue #1386.

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
 at file:///app/node_modules/@nextui-org/tooltip/dist/chunk-MA2FG3JE.mjs:29:7
 at file:///app/node_modules/@nextui-org/snippet/dist/chunk-DMESSLTO.mjs:36:18
 at div
 at file:///app/node_modules/@nextui-org/snippet/dist/chunk-DMESSLTO.mjs:34:7
```

https://github.com/nextui-org/nextui/blob/12cebcfdac525abc4debf7cee45166c840265b11/packages/components/tooltip/src/use-tooltip.ts#L183-L187

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-7urocq?file=README.md

### Steps to Reproduce the Bug or Issue

1. open the Stackblitz example
2. run `npm run start` in the Stackblitz terminal
3. navigate to `/` (index) page
4. the terminal output should now include a `useLayoutEffect` warning

### Expected behavior

I would expect that the `Tooltip` component does not call the `useLayoutEffect` hook inside a SSR environment.

### Screenshots or Videos

image

### Operating System Version

Linux

### Browser

Other (add additonal context)

### PR DESCRIPTION
**Pull request by friedemannsommer**
Closes #1954

## 📝 Description

These changes address the React SSR warning "useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format." for the [tooltip component](https://github.com/nextui-org/nextui/blob/12cebcfdac525abc4debf7cee45166c840265b11/packages/components/tooltip/src/use-tooltip.ts#L183-L187).

## ⛳️ Current behavior (updates)

As described in the issue (#1954) React will log a warning.

## 🚀 New behavior

By using the `useSafeLayoutEffect` function (which checks whether an HTML document exists and, if not, uses the `useEffect` hook as a fallback), no React warning is logged.

## 💣 Is this a breaking change (Yes/**No**):

In my opinion this shouldn't be a breaking change, since it adds a (technically) internal runtime dependency (which wasn't used before) and imports it in the relevant file (`use-tooltip.ts`).

## 📝 Additional Information

I couldn't get the "changeset" (`Command "changeset" not found`) command to work on my machine.
Commands i've tried:
* `pnpm changeset`
* `pnpx changeset`

### CODE REVIEW

**Review by jrgarciadev — APPROVED** [review]
Thank you! @friedemannsommer 🙏🏻

**Comment by jrgarciadev** [comment]
@friedemannsommer could you please update the .lock file? Run `pnpm install` at the root. of the project and push those changes to avoid the `install` CI step failing

**Comment by friedemannsommer** [comment]
@jrgarciadev I'm sorry about that, I really thought I had already done that.

**Comment by luixo** [comment]
Hi,
Can this be merged? Seems like a minor change.

**Comment by luixo** [comment]
@friedemannsommer Do you mind updating the .lock file?

**Comment by friedemannsommer** [comment]
@luixo Sure, after merging the latest "main" branch there don't seem to be any changes necessary?

**Comment by luixo** [comment]
I hope so.
Waiting for @jrgarciadev now.

**Review by jrgarciadev — APPROVED** [review]
Thank you! @friedemannsommer 🙏🏻

**Pull request merged**
