### PR TITLE
types(core): allow Promise<void> for provider navigate prop

### PR DESCRIPTION
**Pull request by CanRau**
## 📝 Description

At least TanStack Router's `router.navigate` returns `Promise<void>` so if this PR won't break anything would be nice to support both return types ❤️ 

## ⛳️ Current behavior (updates)

```
Type '(to: any, options: any) => Promise<void>' is not assignable to type '(path: string) => void'.
```

The `to: any, options: any` is another topic I think

## 🚀 New behavior

No type errors

## 💣 Is this a breaking change (Yes/No):

Shouldn't break anything I think 🤔 

## Summary by CodeRabbit

- **New Features**
	- Enhanced the `navigate` function to support asynchronous operations by allowing it to return a promise.
  
This change improves flexibility in navigation handling within the application.

### CODE REVIEW

**Comment by jrgarciadev** [comment]
@wingkwong please review

**Review by wingkwong — CHANGES_REQUESTED** [review]
please get rid of those unrelated changes. You may branch out of `canary` or `nextui-org:beta/release-next`.

**Comment by CanRau** [comment]
Oh wow didn't realize, just made this change here in the GitHub editor, I'll have a look a little later

**Comment by wingkwong** [comment]
@CanRau I think the reason is your `patch-2` branch was branched out from our `main` branch. Currently we haven't synced that to `canary`.

**Comment by CanRau** [comment]
Alright, sorry for the delay I'll look into it tomorrow (Monday)

**Comment by CanRau** [comment]
Redid the PR cause it was quicker 😇 
https://github.com/nextui-org/nextui/pull/4112

**Pull request closed without merging**
