### PR TITLE
Creating documentation for Image component

### PR DESCRIPTION
**Pull request by heysagnik**
🚧Work in progress 🚧

## [LEVEL]/[COMPONENT]
**TASK**: Added a documentation for Image component 

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Only
- [ ] Refactor

### Description, Motivation and Context
I thought that Next-UI didn't have any Image component ,as it wasn't mentioned in documentation !Later I asked the community and they confirmed me Next UI has its Image component too! 
So I am thinking to add a documentation for Image component

### CODE REVIEW

**Comment by devgossips** [comment]
Please don't merge this , I am working on this 🚧🚧

**Comment by jrgarciadev** [comment]
Amazing 🚀 , thank you so much @devgossips looking forward to this

**Comment by jrgarciadev** [comment]
Hey @heysagnik any updates on this?

**Comment by heysagnik** [comment]
I was busy these days , So can't be active too much . I will soon update it

**Comment by jrgarciadev** [comment]
Hey @heysagnik, sorry but we had to implement this by ourselves, thank you anyway ✋🏻

**Pull request closed without merging**
