### PR TITLE
Feat/select

### PR DESCRIPTION
**Pull request by amauryfischer**
## 📝 Description

> Add a Select Component to next-ui

## 💣 Is this a breaking change (Yes/No):
It's not a breaking change

## 📝 Additional Information
This is just a proposal for now there is a lot of remaining work to get something usable.

### CODE REVIEW

**Comment by amauryfischer** [comment]
@jrgarciadev this is a first approach to get a Select on next-ui, as this is my first contribution, i supposed there is a lot to change before the PR will be accepted, i'm open to any comment ! :) feel free to review

**Comment by ShellarFX** [comment]
@amauryfischer i think it might be better to use `react-aria` instead of `react-stately` since NextUI migrates to `react-aria`
https://github.com/orgs/nextui-org/projects/2/views/2?pane=issue&itemId=13762964

**Comment by hmbrg** [comment]
> @amauryfischer i think it might be better to use `react-aria` instead of `react-stately` since NextUI migrates to `react-aria` https://github.com/orgs/nextui-org/projects/2/views/2?pane=issue&itemId=13762964

@ShellarFX  `react-stately` is part of `react-aria`: https://react-spectrum.adobe.com/react-stately/index.html

**Comment by ShellarFX** [comment]
> > @amauryfischer i think it might be better to use `react-aria` instead of `react-stately` since NextUI migrates to `react-aria` https://github.com/orgs/nextui-org/projects/2/views/2?pane=issue&itemId=13762964
> 
> @ShellarFX `react-stately` is part of `react-aria`: https://react-spectrum.adobe.com/react-stately/index.html

ohh okay, my bad, I think it’s okay then

**Comment by renanmachad** [comment]
@jrgarciadev  What is make to add this feature to library? How i can help this PR to main version
?

**Comment by jrgarciadev** [comment]
Hey @amauryfischer I appreciate the effort you put to send this PR, however as you might know we migrated from Stitches to TailwindCSS, here's the in-progress Select based on top of TailwindCSS and the new structure. Thanks!

**Comment by amauryfischer** [comment]
@jrgarciadev No problem ! i love the new nextuiv2 and i'm glad to see that you worked on Select Feature :)

**Pull request closed without merging**
