### PR TITLE
fix: resolve circle depents in docs

### PR DESCRIPTION
**Pull request by sun0day**
## 📝 Description

> Add a brief description

`yarn dev:docs` failed due to circle depents.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

error above disappeared.

### CODE REVIEW

**Comment by jrgarciadev** [comment]
@tianenpang this issue happen to you? I couldn't replicate it 🤔

**Comment by tianenpang** [comment]
I can't reproduce it either 🤔 hey @sun0day please remove `node_modules` and cache then try again.

```bash
# Remove all node_modules and cache include sub-dirs
find . '(' -name "node_modules" -o -name ".next" -o -name ".turbo" ')' -type d -prune -exec rm -rf '{}' +

# Install deps and build nextui
yarn && yarn build:nextui

# Restart docs dev server
yarn dev:docs
```

**Review by tianenpang — COMMENTED** [review]
I can't reproduce it either 🤔 hey @sun0day please remove `node_modules` and cache then try again.

```bash
# Remove all node_modules and cache include sub-dirs
find . '(' -name "node_modules" -o -name ".next" -o -name ".turbo" ')' -type d -prune -exec rm -rf '{}' +

# Install deps and build nextui
yarn && yarn build:nextui

# Restart docs dev server
yarn dev:docs
```

**Comment by sun0day** [comment]
> 

This error disappeared after cleaning cache and reinstalling dependencies.  But still, I think using circle depents is bad practice. We should avoid circle depents in case of some weird exceptions.

**Comment by tianenpang** [comment]
I agree with you, but I think this error may be caused by other issues 🤔 and for the circular dependency, it's possible to use the webpack plugin to detect it automatically.

**Comment by sun0day** [comment]
I am pretty sure this origin reason is circular depents due to the exception description and my debug process. But the circular depents exception not always occurs, it depends the node_modules' physical topology,  `yarn` can't guarantee node_modules' topology always be the same every time you install or add new dependencies, especially when you host has node_modules cache.

And maybe we can  use eslint rule [import/no-cycle](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md) to discover the circular depends problems in dev stage.

**Comment by jrgarciadev** [comment]
Hey @sun0day I'll close this PR until we can reproduce it in a better way

**Pull request closed without merging**
