### PR TITLE
docs(searchbox): visibility enhancement and blur backdrop

### PR DESCRIPTION
**Pull request by abhinandan-verma**
## 📝 Description

 Search Box Border contrast enhancement in dark mode & blur backdrop

## ⛳️ Current behavior (updates)

Screenshot 2024-07-17 at 1 07 11 AM

## 🚀 New behavior

Screenshot 2024-07-17 at 1 06 43 AM

## Summary by CodeRabbit

- **Style**
  - Improved border color styles for the `Cmdk` component, including hover states and dark mode, enhancing the visual appearance.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
doesn't look good

image

**Comment by wingkwong** [comment]
I disagree. Besides, you can see the input got a black background and magnifying glass icon got a transparent background.

**Comment by abhinandan-verma** [comment]
then it's ok to use the prev one, I  just put it, because I found a contrast issue  b/w border and background.
we can just use the `blur` backdrop

**Comment by wingkwong** [comment]
as spoken, let's keep it as it is

**Pull request closed without merging**
