### PR TITLE
refactor(docs): adjust positioning of floating components

### PR DESCRIPTION
**Pull request by ladunjexa**
## 📝 Description

> Add a brief description

Adjust positioning of the widgets within floating components in the media queries large-to-2xl for improving ui and ux.

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

In the media queries large-to-2xl, the widgets are arranged in a different way, In addition, the image hides one of the features in the `GridFeatures` component (for this, only need to set z-index to the `GridFeatures` div) but I chose to offer a different arrangement for those media-queries, which might be suitable for you.

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

[Here](https://streamable.com/e/hqjakw) is a demonstration video showing how it looks before and after. (on 1920x1080 display)

## 💣 Is this a breaking change (Yes/No):

No.

## Summary by CodeRabbit

- **New Features**
  - Enhanced responsiveness for Floating Components and Floating Tabs to improve display across larger screens.

- **Style**
  - Updated positioning, animations, and sizes of various elements to adapt better to different screen sizes.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
the demo video is not available. please attach a before and after screenshot.

**Comment by ladunjexa** [comment]
> the demo video is not available. please attach a before and after screenshot.

[here](https://streamable.com/tgotdk)👍

**Comment by wingkwong** [comment]
I think your forked repo is pretty outdated. Can you sync once with our latest canary and check if the fix is still required?

**Comment by ladunjexa** [comment]
> I think your forked repo is pretty outdated. Can you sync once with our latest canary and check if the fix is still required?

Yeah the fix is still required, the vid I uploaded yestetday - recorded yesterday. The PR have no conflicts, so I think it's okay merge this PR.

**Comment by wingkwong** [comment]
> This branch is [1 commit ahead of](https://github.com/ladunjexa/nextui/compare/nextui-org%3Anextui%3Acanary...fix/floating-components), [183 commits behind](https://github.com/ladunjexa/nextui/compare/fix/floating-components...nextui-org%3Anextui%3Acanary) nextui-org/nextui:canary.

Please sync once so that I could review on PR build.

**Comment by ladunjexa** [comment]
> > This branch is [1 commit ahead of](https://github.com/ladunjexa/nextui/compare/nextui-org%3Anextui%3Acanary...fix/floating-components), [183 commits behind](https://github.com/ladunjexa/nextui/compare/fix/floating-components...nextui-org%3Anextui%3Acanary) nextui-org/nextui:canary.
> 
> Please sync once so that I could review on PR build.

My mistake, I thought I had already synced it yesterday. I just did. 👍

**Review by ladunjexa — COMMENTED** [review]
.

**Comment by wingkwong** [comment]
With width = 1920, the current documentation looks different than your video. Also We don't use max-2xl given the mobile first principle.

image

**Pull request closed without merging**
