### PR TITLE
fix(dropdown): respect closeOnSelect prop on DropdownItem

### LINKED ISSUE #2290: Dropdown Unexpectedly Closes on Item Selection Despite closeOnSelect Being Set to False
### NextUI Version

2.2.9

### Describe the bug

I'm experiencing an unexpected behavior with the closeOnSelect property in a `DropdownItem` component. Contrary to the expected functionality, the Dropdown closes upon the item selection, even though `closeOnSelect` is explicitly set to `false`.

### Your Example Website or App

https://codesandbox.io/p/devbox/dazzling-williams-x2q5sh

### Steps to Reproduce the Bug or Issue

1. create a  `DropdownItem` component with multiple selectable items.
2. Explicitly set the `closeOnSelect` property to false for a `DropdownItem`.
3. Notice that the Dropdown menu closes upon the selection, contrary to the expected behavior.

### Expected behavior

When `closeOnSelect` is set to false, selecting the item with `closeOnSelect`  should not close the Dropdown menu.

### Screenshots or Videos

_No response_

### Operating System Version

macOS (13.6.3)

### Browser

Edge

### PR DESCRIPTION
**Pull request by gtoxlili**
Closes #2290

## 📝 Description

This PR fixes an issue where the `closeOnSelect` prop on `DropdownItem` was being overridden by the `DropdownMenu` settings, causing the dropdown to close even when `closeOnSelect` was set to `false` on an individual `DropdownItem`.

## ⛳️ Current behavior (updates)

Currently, setting `closeOnSelect` to `false` on a `DropdownItem` does not prevent the dropdown from closing when that item is selected. This is because the `onAction` event handler on `DropdownItem` is deprecated and the closing behavior is controlled by the `DropdownMenu` settings.

## 🚀 New behavior

The logic has been updated to respect the `closeOnSelect` prop on `DropdownItem`. Now, if `closeOnSelect` is set to `false` on a `DropdownItem`, selecting that item will not close the dropdown menu.

The relevant changes are:

```diff
+ const onAction = (key: Key) => {
+   if (closeOnSelect) {
+     onTopAction?.(key);
+   }
+ };
```

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

N/A

## Summary by CodeRabbit

- **New Features**
	- Introduced nuanced handling of the `closeOnSelect` property for dropdown items, allowing them to remain open or close based on user selection.
	- Added a new template to showcase dropdown behavior with the `closeOnSelect` property.
- **Bug Fixes**
	- Addressed an issue related to the `closeOnSelect` prop in the dropdown component.
- **Tests**
	- Added tests to verify the behavior of the `closeOnSelect` property in the DropdownItem component.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
1. please add a changeset
2. please provide before & after videos to demonstrate if possible

**Comment by gtoxlili** [comment]
> 1. please add a changeset
> 2. please provide before & after videos to demonstrate if possible

Thanks for the reminder, I've added the changeset.

**Comment by KoJem9Ka** [comment]
Really waiting for this fix in the release)

**Review by wingkwong — CHANGES_REQUESTED** [review]
Just tested with the same code from the issue, the menu is still closed after clicking New file. Also please add tests to cover this case.

```tsx
<Dropdown>
  <DropdownTrigger>
    <Button variant="bordered">Open Menu</Button>
  </DropdownTrigger>
  <DropdownMenu aria-label="Static Actions">
    <DropdownItem key="new" closeOnSelect={false}>
      New file
    </DropdownItem>
    <DropdownItem key="copy">Copy link</DropdownItem>
    <DropdownItem key="edit">Edit file</DropdownItem>
    <DropdownItem key="delete" className="text-danger" color="danger">
      Delete file
    </DropdownItem>
  </DropdownMenu>
</Dropdown>
```

**Comment by gtoxlili** [comment]
Currently, if a `DropdownItem` has `closeOnSelect` explicitly set to `false`, the menu will remain open when that item is selected. Otherwise, it follows the `DropdownMenu`'s `closeOnSelect` setting.

I have added the relevant templates. Please test the changes based on the provided templates.

@wingkwong

**Comment by wingkwong** [comment]
@gtoxlili apart from storybook, I was asking for tests to be added in `/packages/components/dropdown/__tests__/dropdown.test.tsx`

**Comment by gtoxlili** [comment]
> @gtoxlili apart from storybook, I was asking for tests to be added in `/packages/components/dropdown/__tests__/dropdown.test.tsx`

Added

**Review by wingkwong — CHANGES_REQUESTED** [review]
Tests are not passing. Please check.

**Comment by gtoxlili** [comment]
> Tests are not passing. Please check.

It passes on my local machine, can you show me your test cases?

**Comment by wingkwong** [comment]
@gtoxlili just look at the [QA / Tests (pull_request)](https://github.com/nextui-org/nextui/actions/runs/8843938893/job/24548469839?pr=2598). Already tried rerunning few times. I think your branch is out of sync. Please sync once with `canary` and re-run the tests.

image

**Comment by gtoxlili** [comment]
> @gtoxlili just look at the [QA / Tests (pull_request)](https://github.com/nextui-org/nextui/actions/runs/8843938893/job/24548469839?pr=2598). Already tried rerunning few times. I think your branch is out of sync. Please sync once with `canary` and re-run the tests.
> 
> image

I have already merged the canary branch into my fix branch and re-executed all the tests for the dropdown. These are the results on my local machine, and I still haven't found any errors. I don't have any clue how to solve this problem. If possible, perhaps you could provide me with some more detailed information?

CleanShot 2024-05-06 at 18 34 49@2x

**Comment by gtoxlili** [comment]
The previous changes I proposed indeed had some issues. I have fixed them, uploaded the updated version, and conducted further testing. @wingkwong

**Comment by gtoxlili** [comment]
The main reason for the issue is that the component's previous design coupled the onAction and closeOnSelect behaviors.

const getMenuProps = <T>(
  props?: Partial<MenuProps<T>>,
  _ref: Ref<any> | null | undefined = null,
) => {
  return {
    ref: mergeRefs(_ref, menuRef),
    menuProps,
    closeOnSelect,
    ...mergeProps(props, {
      onAction: () => onMenuAction(props?.closeOnSelect),
      onClose: state.close,
    }),
  } as MenuProps;
};

In the previous design, the user-provided onAction was merged with the close event based on DropdownMenu's closeOnSelect using mergeProps. The merged onAction was then passed to the item. When the event was triggered, the item directly executed the onAction method passed from the menu. (This is also the reason why the closeOnSelect of the item component was ineffective.)

My previous modification did not consider the possibility of the user passing their own onAction. So, I chose to directly skip executing the onAction passed from DropdownMenu if the item had closeOnSelect. (I assumed mergeProps was an override-like setting, but it turned out to execute all events with the same name in sequence.)

Now, I have changed the close event to:

onAction: (key: any) => {
  // @ts-ignore
  const item = props?.children?.find((item) => item.key === key);

  if (item?.props?.closeOnSelect === false) {
    onMenuAction(false);

    return;
  }
  onMenuAction(props?.closeOnSelect);
}

Since the item passes its key when triggering onAction, I try to find whether it has closeOnSelect based on the key. I think this logic should be correct now (although the logic is still messy, mainly because this coupled design is not a good design).

**Comment by gtoxlili** [comment]
The main reason for the issue is that the component's previous design coupled the onAction and closeOnSelect behaviors.
```
const getMenuProps = <T>(
  props?: Partial<MenuProps<T>>,
  _ref: Ref<any> | null | undefined = null,
) => {
  return {
    ref: mergeRefs(_ref, menuRef),
    menuProps,
    closeOnSelect,
    ...mergeProps(props, {
      onAction: () => onMenuAction(props?.closeOnSelect),
      onClose: state.close,
    }),
  } as MenuProps;
};
```
In the previous design, the user-provided onAction was merged with the close event based on DropdownMenu's closeOnSelect using mergeProps. The merged onAction was then passed to the item. When the event was triggered, the item directly executed the onAction method passed from the menu. (This is also the reason why the closeOnSelect of the item component was ineffective.)

My previous modification did not consider the possibility of the user passing their own onAction. So, I chose to directly skip executing the onAction passed from DropdownMenu if the item had closeOnSelect. (I assumed mergeProps was an override-like setting, but it turned out to execute all events with the same name in sequence.)

Now, I have changed the close event to:
```
onAction: (key: any) => {
  // @ts-ignore
  const item = props?.children?.find((item) => item.key === key);

  if (item?.props?.closeOnSelect === false) {
    onMenuAction(false);

    return;
  }
  onMenuAction(props?.closeOnSelect);
}
```
Since the item passes its key when triggering onAction, I try to find whether it has closeOnSelect based on the key. I think this logic should be correct now (although the logic is still messy, mainly because this coupled design is not a good design).

**Review by wingkwong — APPROVED** [review]

**Comment by jrgarciadev** [comment]
Hey @gtoxlili please fix the conflicts

**Review by jrgarciadev — APPROVED** [review]

**Comment by jrgarciadev** [comment]
@gtoxlili sorry for the delay, please fix the conflicts

**Pull request merged**
