### PR TITLE
fix: updated z-index to 0 for image component

### LINKED ISSUE #3400: [BUG] - z-index of Image tag is 10
### NextUI Version

2.4.1

### Describe the bug

Image tag has Tailwind z-10

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Set a Header bar fixed at the top of the screen
2. When scroll Image tag up, Image is over the Header

### Expected behavior

I expected z-index of Image tag is 0

### Screenshots or Videos

_No response_

### Operating System Version

Windows 11

### Browser

Chrome

### PR DESCRIPTION
**Pull request by naveen-nrj**
Closes #3400 

## 📝 Description

> updated z-index to 0 for image component

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## Summary by CodeRabbit

- **Style**
	- Adjusted the z-index of the image component to improve its layering and visibility within the UI.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
please provide the code you used to tested with.

**Comment by naveen-nrj** [comment]
> please provide the code you used to tested with.

Hey can you please give some more details as to what code is needed from me.  Thanks

**Comment by wingkwong** [comment]
@naveen-nrj how did you test it?

**Comment by wingkwong** [comment]
Closing - inactivity.

**Pull request closed without merging**
