### PR TITLE
fix(select): prevent default browser error UI from appearing

### LINKED ISSUE #3913: [BUG] - Add `validationBehavior` support for Select
### NextUI Version

2.4.8

### Describe the bug

`Input` and `Select` validation behaviour is different. 

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

When I set `isRequired` on both `Input` & `Select`, the select dropdown uses HTML built-in validation. However, the input box doesn't.

From the screenshots below, you can see the validation error pops up for `Select`, but not for `Input`

### Expected behavior

They should behave in the same way.

### Screenshots or Videos

Screenshot 2024-10-18 at 2 43 12 PM
Screenshot 2024-10-18 at 2 44 26 PM

### Operating System Version

Mac

### Browser

Chrome

### PR DESCRIPTION
**Pull request by chirokas**
Closes #3913

## 📝 Description

See https://github.com/nextui-org/nextui/issues/3913#issuecomment-2441678438

## Summary by CodeRabbit

- **New Features**
  - Improved error handling for the select component, preventing default browser error messages.
  - Enhanced functionality of the hidden select component, including better management of required fields and selected values.

- **Bug Fixes**
  - Fixed the `onChange` handler to properly update the selected keys in the state.

- **Tests**
  - Added a new test suite to validate required field behavior in the select component.

### CODE REVIEW

**Comment by jrgarciadev** [comment]
@wingkwong please review

**Review by wingkwong — CHANGES_REQUESTED** [review]
supposedly submit should be blocked if `validationBehavior` is `native`. now with this PR change, it makes native validation same as `aria`, which means i can submit the form without a value while the field is required.

also please add tests.

**Review by wingkwong — CHANGES_REQUESTED** [review]
now aria behaviour becomes native one. please test both case.

**Comment by chirokas** [comment]
@wingkwong Select doesn't support the `validationBehavior` prop.
https://github.com/nextui-org/nextui/blob/c6326d169dd37790952645ebe3196596f0ae274b/packages/hooks/use-aria-multiselect/src/use-multiselect-state.ts#L77-L83
https://github.com/nextui-org/nextui/issues/3913#issuecomment-2459740356

**Comment by chirokas** [comment]
Opening a new one - #4281

**Pull request closed without merging**
