### PR TITLE
v2.3.0 [WIP]

### LINKED ISSUE #1662: [Feature Request] Calendar 🗓️
### Is your feature request related to a problem? Please describe.

calenders are one the most important components to have and hard to build, it would be nice to have, I've been using nextui for a long time now, and I love it, but each time I need to implement something that includes working white date pickers I have to relie on other libraries which is not ideal.
Thanks.

### Describe the solution you'd like

- normal date picker based on the react area ones
- calendar with time
- date range picker
- calendar with dropdown presets (if applicable)

### Describe alternatives you've considered

React DayPicker

### Screenshots or Videos

_No response_

### LINKED ISSUE #1969: [BUG] - react-hook-form
### NextUI Version

2.2.9

### Describe the bug

`

<Input
          type="text"
          placeholder="0"
          classNames={{
            input: "text-right",
          }}
          radius="none"
          onValueChange={(value: string) => inputChange(value, "amount")}
          size="sm"
          {...register("amount", {
            required: true,
          })}
    />
`

It uses React-hook-form and next ui input, and is initialized when the value is entered with setValue.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

""

### Expected behavior

""

### Screenshots or Videos

_No response_

### Operating System Version

masOs

### Browser

Chrome

### LINKED ISSUE #2249: [Feature Request] We really need a datepicker and a calendar component
### Is your feature request related to a problem? Please describe.

its really hard to input dateTime and show schedule now

### Describe the solution you'd like

need a datepicker and a calendar

### Describe alternatives you've considered

need a datepicker and a calendar

### Screenshots or Videos

_No response_

### LINKED ISSUE #2511: [Feature Request] calendar with custom styles
### Is your feature request related to a problem? Please describe.

it's possible to customizar calendar popup in <Input type="data" .../> component?

### Describe the solution you'd like

...

### Describe alternatives you've considered

i need to change text to spanish

### Screenshots or Videos

_No response_

### LINKED ISSUE #2515: [BUG] - Nextui tooltip error
### NextUI Version

2.0.10

### Describe the bug

<Tooltip content="Total number of operating days">
                  <Button variant="flat" className="border rounded-xl px-4 py-2 text-gray-900 flex space-x-2 justify-center items-center">
                    content
                  </Button>
                </Tooltip>
When moving or doing nothing it will display the following error message:
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.6),scale(0.61547),scale(0.65082),scale(0.69443),scale(0.73944),scale(0.78204),scale(0.82036),scale(0.85368),scale(0.88195),scale(0.90551),scale(0.92487),scale(0.94061),scale(0.95328),scale(0.9634),scale(0.97144),scale(0.97779),scale(0.98278),scale(0.98668),scale(0.98973),scale(0.99209),scale(0.99393),scale(0.99534),scale(0.99644),scale(0.99728),scale(0.99792),scale(0.99842),scale(0.99879),scale(0.99908),scale(0.9993),scale(0.99947),scale(1)

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

Move between two Tooltip blocks quickly or do nothing

### Expected behavior

Fix this bug in the next update

### Screenshots or Videos

image

https://github.com/nextui-org/nextui/assets/75132211/8131af32-c5fe-4f89-9797-4c1f64506a62

### Operating System Version

Window 11 Home

### Browser

Chrome

### LINKED ISSUE #2519: [BUG] - Framer Motion ^11 "Error: Only two keyframes currently supported with spring and inertia animations" on Popover and Select
### NextUI Version

2.2.9

### Describe the bug

When using Framer Motion 11, if you open and close a Popover quickly (before the animation ends), the following error gets thrown:

`
Error: Only two keyframes currently supported with spring and inertia animations. Trying to animate scale(0.8),scale(0.80774),scale(0.82541),scale(0.84721),scale(0.86972),scale(0.89102),scale(0.91018),scale(0.92684),scale(0.94097),scale(0.95275),scale(0.96244),scale(0.9703),scale(0.97664),scale(0.9817),scale(0.98572),scale(0.9889),scale(0.99139),scale(0.99334),scale(0.99486),scale(0.99605),scale(0.99696),scale(0.99767),scale(0.99822),scale(0.99864),scale(0.99896),scale(0.99921),scale(0.9994),scale(0.99954),scale(0.99965),scale(0.99974),scale(1)`

This is likely due to the following: https://github.com/framer/motion/issues/2190#issuecomment-1878437924
> Spring/inertia has never worked with multiple keyframes (you can see in the working animation the animation settings aren't actually taking effect). Adding this support is unlikely but I can make a better error message.

The error will only be thrown in a dev environment and was introduced here framer/motion#2474. I have only tested this on the Select and Popover components and can confirm both throw the same error.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Use either a popover or select component
```jsx
import {Popover, PopoverTrigger, PopoverContent} from "@nextui-org/react";
//...
<Popover>
    <PopoverTrigger>Hello</PopoverTrigger>
    <PopoverContent>
        <div>World</div>
    </PopoverContent>
</Popover>
```
2. Click the trigger very quickly, before the animation finishes

### Expected behavior

I expect the popover to be able to open and close quickly, without error. 

### Screenshots or Videos

_No response_

### Operating System Version

Windows

### Browser

Chrome

### LINKED ISSUE #2585: [BUG] - Form submission doesn't respect isRequired attribute of RadioGroup
### NextUI Version

2.2.10

### Describe the bug

When using the isRequired={true} attribute on a RadioGroup, the form submission is not being prevented. According to the documentation, setting isRequired={true} should enforce the requirement for at least one option to be selected before submitting the form. However, in the current implementation, the form submission proceeds even if no radio button is selected.

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-7ybdjp?file=app%2Fpage.tsx

### Steps to Reproduce the Bug or Issue

1. Navigate to the form containing the RadioGroup component.
2. Attempt to submit the form without selecting any radio button.
3. Observe that the form submission is not prevented, and the submission proceeds.

### Expected behavior

When attempting to submit the form without selecting any option in the RadioGroup component, the form submission should be prevented.

### Screenshots or Videos

image

### Operating System Version

Windows

### Browser

Chrome

### LINKED ISSUE #2662: [BUG] - AvatarGroup max count avatar doesn't match the style of other avatars
### NextUI Version

2.2.10

### Describe the bug

The `<AvatarGroup/>` component supports a `max` property to limit the number of avatars shown. It will generate an avatar with a label like "+3" to indicate how many avatars are not displayed. However, this generated avatar does not match the style of the other avatars that are defined in the group. For example, the `size`, `radius`, and also `classNames` styles are not used for the generated avatar.

Note: this also applies to the `total` property on `<AvatarGroup/>`.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

The following code takes the AvatarGroup max count example from the [NextUI docs](https://nextui.org/docs/components/avatar#group-max-count) and adds a `classNames` property to add a colored border, a `radius` property to change the radius on each avatar, and a `size` property to produce smaller avatars. 

```
import React from "react";
import {Avatar, AvatarGroup} from "@nextui-org/react";

export default function App() {
  return (
    <AvatarGroup isBordered max={3}>
      <Avatar classNames={{ base: "border-2 border-yellow-400" }} radius="sm" size="sm" src="https://i.pravatar.cc/150?u=a042581f4e29026024d" />
      <Avatar classNames={{ base: "border-2 border-yellow-500" }} radius="sm" size="sm" src="https://i.pravatar.cc/150?u=a04258a2462d826712d" />
      <Avatar classNames={{ base: "border-2 border-yellow-500" }} radius="sm" size="sm" src="https://i.pravatar.cc/150?u=a042581f4e29026704d" />
      <Avatar classNames={{ base: "border-2 border-yellow-500" }} radius="sm" size="sm" src="https://i.pravatar.cc/150?u=a04258114e29026302d" />
      <Avatar classNames={{ base: "border-2 border-yellow-500" }} radius="sm" size="sm" src="https://i.pravatar.cc/150?u=a04258114e29026702d" />
      <Avatar classNames={{ base: "border-2 border-yellow-500" }} radius="sm" size="sm" src="https://i.pravatar.cc/150?u=a04258114e29026708c" />
    </AvatarGroup>
  );
}
```

### Expected behavior

I would expect that the generated avatar that says "+3" would use the same style as the avatars in the group, to produce a consistent design where all of the grouped elements look the same and are sized equally.

In the general case, it's possible that different avatars in the group could have different styles, which would make the decision on which style to use difficult. Though in practice, most users will use a `map` over an array of user data objects, which will produce a consistent style for each avatar. Even a simple solution, such as using the style of the first avatar, or the last shown avatar, would effectively solve this issue, I believe. Another solution would be to provide a way for the user to style the generated button directly.

### Screenshots or Videos

avatargroup

### Operating System Version

macOS Sonoma 14.2.1

### Browser

Chrome

### PR DESCRIPTION
**Pull request by jrgarciadev**
### v2.3.0

Summary:

- [x] fix(radio): isRequired & missing warning message in Form (#2597)
  - Closes #2585
  - avoid overriding required prop
  - merge with domRef to keep `validationMessage`
- [x] feat(avatar): support slots in AvatarGroup
   -  Closes #2662 2662
- [x] fix: only two keyframes currently supported with spring and inertia animations (#2596)
   - Closes #2519
   - Closes #2515
   - Closes: #2690
   - Framer Motion previously introduced a bug in v11 and NextUI was stuck using v10. Framer motion team fixed that and released 13 hours ago. This PR is to bump to frame motion version to include that fix.
- [x] fix: react hook form issue (#2603)
  - Closes #1969
  - handle RHF on NextUI Form component(input, checkbox, select, autocomplete)
- [x] Upgrade to new react aria version #2561
  - Closes: #2360
- [x] Calendar component
   -  Closes #555 
   -  Closes #1662 
   -  Closes #1664 
   -  Closes #2511 
   -  Closes #2249
   - [x] Core (#2456)
   - [x]  Docs (#2686)
- [x] Range Calendar component 
   - [x] Core (#2634)
   - [x] Docs (#2686)
 - [x] Date Input component
   - [x] Core (#2641)
   - [x] Docs (#2711) 
 - [x] TimeInput component
   - [x] Core (#2672)
   - [x] Docs (#2698)
 - [x] Date Picker component
   - Closes: #1995
   - ref: #2571
   - [x] Core (#2652) 
   - [x] Docs (#2700) 
 - [x] Date Range Picker component
    - [x] Core (#2682) [in progress]
    - [x] Docs (#2712) 

### New Tools

CLI (https://github.com/nextui-org/nextui/pull/2714)

### Breaking changes

Units variables were removed in favour of TailwindCSS' `min-h` `max-h` new units (#2713)

https://tailwindcss.com/blog/tailwindcss-v3-4
https://tailwindcss.com/docs/min-width
https://tailwindcss.com/docs/min-height

## ⛳️ Current behavior (updates)

```jsx
import {Button} from "@nextui-org/react";

export const MyButton = () => {
  return (
    <Button className="px-unit-2 py-unit-1 min-w-unit-3xl">
      My Button
    </Button>
  );
}
```

## 🚀 New behavior

```jsx
import {Button} from "@nextui-org/react";

export const MyButton = () => {
  return (
    <Button className="px-2 py-1 min-w-3xl">
      My Button
    </Button>
  );
}
```

## 💣 Is this a breaking change (Yes/No): Yes

- Upgrade tailwindcss to v3.4

- Replace `-unit-` by `-`

```diff
- <Button className="px-unit-2 py-unit-1 min-w-unit-3xl">
+ <Button className="px-2 py-1 min-w-3xl"> 
```

### CODE REVIEW

**Comment by jrgarciadev** [comment]
@wingkwong please add the `Closes #` issues and added changes

**Comment by mihainiculai** [comment]
Is it normal for calendar to have that scroll slidebars?

Screenshot 1
Screenshot 2

**Comment by wingkwong** [comment]
@mihainiculai are you using Windows?

image

**Comment by mihainiculai** [comment]
@wingkwong yap, Google Chrome on Windows 11 show scrollbars

**Comment by kuri-sun** [comment]
🥳

**Pull request merged**
