### PR TITLE
Update getting-started.mdx

### LINKED ISSUE #441: Error in Documentation for _document.tsx
### Describe the bug

heres the code from the docs
```tsx
import Document, {
  Html,
  Head,
  Main,
  NextScript,
  DocumentContext,
  DocumentInitialProps,
} from "next/document";
import { CssBaseline } from "@nextui-org/react";
import { ReactElement } from "react";

class MyDocument extends Document {
  static async getInitialProps(
    ctx: DocumentContext
  ): Promise<DocumentInitialProps> {
    const initialProps = await Document.getInitialProps(ctx);
    return {
      ...initialProps,
      styles: <>{initialProps.styles}</>,
    };
  }

  render() {
    return (
      <Html lang="en">
        <Head>{CssBaseline.flush()}</Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    );
  }
}

export default MyDocument;
```
i get a type error at this line `styles: <>{initialProps.styles}</>,` saying `Type 'Element' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>[] | ReactFragment | undefined'`

if i remove the <> </> it doesnt show a type error and it works

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

Follow the nextjs guide in the docs https://nextui.org/docs/guide/getting-started#nextjs

### Expected behavior

the documentation should have the correct code

### Screenshots or Videos

_No response_

### Operating System Version

macOS

### Browser

Firefox

### PR DESCRIPTION
**Pull request by anoushk1234**
fixes #441

### CODE REVIEW

**Comment by toinelin** [comment]
> Hey @anoushk1234 thank you so much, could you please write it this way:
> 
> ```js
> import React from 'react';
> 
> // ...
>    return {
>       ...initialProps,
>       styles: (
>         <React.Fragment>
>           {initialProps.styles}
>         </React.Fragment>
>       )
>     };
> 
> // ...
> ```

Hey, got a TypeScript issue using `styles: (<Fragment>{initialProps.styles}</Fragment>)` instead of `styles: [<Fragment>{initialProps.styles}</Fragment>]` + `Fragment` should have a key for proper React rendering

**Comment by toinelin** [comment]
> > > Hey @anoushk1234 thank you so much, could you please write it this way:
> > > ```js
> > > import React from 'react';
> > > 
> > > // ...
> > >    return {
> > >       ...initialProps,
> > >       styles: (
> > >         <React.Fragment>
> > >           {initialProps.styles}
> > >         </React.Fragment>
> > >       )
> > >     };
> > > 
> > > // ...
> > > ```
> > 
> > 
> > Hey, got a TypeScript issue using `styles: (<Fragment>{initialProps.styles}</Fragment>)` instead of `styles: [<Fragment>{initialProps.styles}</Fragment>]` + `Fragment` should have a key for proper React rendering
> 
> Hey @toinelin could you share your `tsconfig.json`?

Sure here it is:
```
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "baseUrl": ".",
    "paths": {
      "@/components/*": [
        "./components/*"
      ],
      "@/contexts/*": [
        "./contexts/*"
      ],
      "@/hooks/*": [
        "./hooks/*"
      ],
      "@/pages/*": [
        "./pages/*"
      ],
      "@/styles/*": [
        "./styles/*"
      ]
    },
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
  "exclude": ["node_modules"]
}

```

**Comment by anoushk1234** [comment]
> ```js
> <React.Fragment>
>           {initialProps.styles}
>         </React.Fragment>
> ```

i'm getting this error ```Type 'Element' is not assignable to type 'ReactElement<any, string | JSXElementConstructor<any>>[] | ReactFragment | undefined'.```

heres my tsconfig https://github.com/anoushk1234/anoushk.xyz/blob/main/tsconfig.json

**Review by jrgarciadev — APPROVED** [review]
Thank you 🙌🏻  @anoushk1234

**Pull request merged**
