### PR TITLE
refactor(docs): default import -> named import

### PR DESCRIPTION
**Pull request by TroyTae**
Closes #579

## 📝 Description

Refactor import code in document

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by jrgarciadev** [comment]
Hey @TroyTae sorry, could you please fix the conflicts?

**Comment by TroyTae** [comment]
@jrgarciadev Done!

**Comment by jrgarciadev** [comment]
Hey @TroyTae thank you!, I forgot to mention to you that for it to work we have to modify the `transformCode` function https://github.com/nextui-org/nextui/blob/main/apps/docs/src/components/playground/utils.ts#L9-L42 which is a mini transpiler that I wrote to join `sandpack` with `react-live`, 

I'm getting this error because of that:

Screen Shot 2022-08-29 at 09 43 09

**Comment by TroyTae** [comment]
@jrgarciadev Oops I'm so sorry
I'm just added react hooks into react-live scope

**Pull request closed without merging**
