### PR TITLE
chore: run pnpm install

### PR DESCRIPTION
**Pull request by simPod**
Closes # 

## 📝 Description

Running `pnpm install --hoist` produces this changeset

## ⛳️ Current behavior (updates)

n/a

## 🚀 New behavior

n/a

## 💣 Is this a breaking change (Yes/No):

no

## 📝 Additional Information

It is confusing to me as a new contributor. Maybe I'm doing something wrong?

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
I couldn't reproduce this change. Can you delete node_modules and reinstall again?

**Comment by simPod** [comment]
I tried `rm -rfd node_modules` but still getting the same lockfile 🤔

**Comment by ryo-manba** [comment]
I couldn't reproduce the issue. Please try running it on the latest main branch.

**Comment by simPod** [comment]
Rebased onto main. still the same issue. however, I'm not familiar with pnp so have no idea why it is happening...

**Comment by kuri-sun** [comment]
I couldn't reproduce the issue either... Thanks!

**Comment by wingkwong** [comment]
Closing - not reproducible

**Pull request closed without merging**
