### PR TITLE
docs(guide): add an explanation for the installation guide

### PR DESCRIPTION
**Pull request by Nozomi-Hijikata**
## 📝 Description
Add an explanation for [the installation page](https://nextui.org/docs/guide/installation)

## ⛳️ Current behavior (updates)
Currently, there is no explanation for users to install packages after initialization.

スクリーンショット 2024-04-18 15 03 01

[current version here](https://nextui.org/docs/guide/installation#automatic-installation)

Therefore, it is possible that users may encounter such situation.

```
❯ nextui init new-nextui-app

NextUI CLI v0.1.5

✔ Select a template › App

✔ Template created successfully!

❯ cd new-nexui-app

❯ npm run dev

> next-app-template@0.0.1 dev
> next dev

sh: next: command not found

```

This is because the dependencies are not installed in the project directory.

``` 
❯ npm list --depth=0
npm ERR! code ELSPROBLEMS
npm ERR! missing: @nextui-org/button@^2.0.28, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/code@^2.0.25, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/input@^2.1.18, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/kbd@^2.0.26, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/link@^2.0.27, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/navbar@^2.0.28, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/snippet@^2.0.32, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/switch@^2.0.26, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/system@2.1.0, required by next-app-template@0.0.1
npm ERR! missing: @nextui-org/theme@2.2.0, required by next-app-template@0.0.1
npm ERR! missing: @react-aria/ssr@^3.9.2, required by next-app-template@0.0.1
npm ERR! missing: @react-aria/visually-hidden@^3.8.10, required by next-app-template@0.0.1
npm ERR! missing: @types/node@20.5.7, required by next-app-template@0.0.1
npm ERR! missing: @types/react-dom@18.2.7, required by next-app-template@0.0.1
npm ERR! missing: @types/react@18.2.21, required by next-app-template@0.0.1
npm ERR! missing: autoprefixer@10.4.19, required by next-app-template@0.0.1
npm ERR! missing: clsx@^2.0.0, required by next-app-template@0.0.1
npm ERR! missing: eslint-config-next@14.2.1, required by next-app-template@0.0.1
npm ERR! missing: eslint@8.48.0, required by next-app-template@0.0.1
npm ERR! missing: framer-motion@^11.1.1, required by next-app-template@0.0.1
npm ERR! missing: intl-messageformat@^10.5.0, required by next-app-template@0.0.1
npm ERR! missing: next-themes@^0.2.1, required by next-app-template@0.0.1
npm ERR! missing: next@14.2.1, required by next-app-template@0.0.1
npm ERR! missing: postcss@8.4.38, required by next-app-template@0.0.1
npm ERR! missing: react-dom@18.2.0, required by next-app-template@0.0.1
npm ERR! missing: react@18.2.0, required by next-app-template@0.0.1
npm ERR! missing: tailwind-variants@^0.1.20, required by next-app-template@0.0.1
npm ERR! missing: tailwindcss@3.4.3, required by next-app-template@0.0.1
npm ERR! missing: typescript@5.0.4, required by next-app-template@0.0.1
next-app-template@0.0.1 /Users/hijikatanozomi/environment/oss-workshop/new-nextui-app
├── UNMET DEPENDENCY @nextui-org/button@^2.0.28
├── UNMET DEPENDENCY @nextui-org/code@^2.0.25
├── UNMET DEPENDENCY @nextui-org/input@^2.1.18
├── UNMET DEPENDENCY @nextui-org/kbd@^2.0.26
├── UNMET DEPENDENCY @nextui-org/link@^2.0.27
├── UNMET DEPENDENCY @nextui-org/navbar@^2.0.28
├── UNMET DEPENDENCY @nextui-org/snippet@^2.0.32
├── UNMET DEPENDENCY @nextui-org/switch@^2.0.26
├── UNMET DEPENDENCY @nextui-org/system@2.1.0
├── UNMET DEPENDENCY @nextui-org/theme@2.2.0
├── UNMET DEPENDENCY @react-aria/ssr@^3.9.2
├── UNMET DEPENDENCY @react-aria/visually-hidden@^3.8.10
├── UNMET DEPENDENCY @types/node@20.5.7
├── UNMET DEPENDENCY @types/react-dom@18.2.7
├── UNMET DEPENDENCY @types/react@18.2.21
├── UNMET DEPENDENCY autoprefixer@10.4.19
├── UNMET DEPENDENCY clsx@^2.0.0
├── UNMET DEPENDENCY eslint-config-next@14.2.1
├── UNMET DEPENDENCY eslint@8.48.0
├── UNMET DEPENDENCY framer-motion@^11.1.1
├── UNMET DEPENDENCY intl-messageformat@^10.5.0
├── UNMET DEPENDENCY next-themes@^0.2.1
├── UNMET DEPENDENCY next@14.2.1
├── UNMET DEPENDENCY postcss@8.4.38
├── UNMET DEPENDENCY react-dom@18.2.0
├── UNMET DEPENDENCY react@18.2.0
├── UNMET DEPENDENCY tailwind-variants@^0.1.20
├── UNMET DEPENDENCY tailwindcss@3.4.3
└── UNMET DEPENDENCY typescript@5.0.4

npm ERR! A complete log of this run can be found in: /Users/hijikatanozomi/.npm/_logs/2024-04-18T05_23_03_039Z-debug-0.log
```

After the installation of dependencies, the `next dev` command works correctly.
```
❯ npm install

added 455 packages, and audited 456 packages in 3s

130 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

> next-app-template@0.0.1 dev
> next dev

 ⚠ Port 3000 is in use, trying 3001 instead.
  ▲ Next.js 14.2.1
  - Local:        http://localhost:3001

 ✓ Starting...
 ✓ Ready in 2.1s

```

## 🚀 New behavior
Add an install process in the guide.
スクリーンショット 2024-04-18 15 14 06

## 💣 Is this a breaking change (Yes/No):

No.

## 📝 Additional Information
Nothing special!

## Summary by CodeRabbit

- **Documentation**
	- Updated the installation guide with instructions for installing dependencies, starting the local server, and developing with NextUI using the CLI.
	- Added instructions for a Next.js project with NextUI and Tailwind CSS.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
there should be a guideline added in CLI output as well.

**Comment by Nozomi-Hijikata** [comment]
@wingkwong 
Thank you for the feedback!  I have addressed your comment.
I appreciate your assistance!


The new version of CLI guide is attached below.
スクリーンショット 2024-04-19 9 55 02

**Comment by wingkwong** [comment]
++ @winchesHe

**Comment by Nozomi-Hijikata** [comment]
@winchesHe @wingkwong 
ping?...
I would be glad if you could check the revision.

**Comment by wingkwong** [comment]
@Nozomi-Hijikata I was putting this on hold because we want the CLI output to be same. Also this needs to be merged after the new CLI output getting merged first. @winchesHe any supplement?

**Comment by Nozomi-Hijikata** [comment]
@wingkwong 
> I was putting this on hold because we want the CLI output to be same.

Then, do you mean that the version of CLI should be included in the output example?

スクリーンショット 2024-04-25 12 49 54

> Also this needs to be merged after the new CLI output getting merged first. 

Okay, I will wait for the new CLI output to be merged first.

**Comment by winchesHe** [comment]
@wingkwong https://github.com/nextui-org/nextui-cli/pull/36 CLI have been merged i think it also can merge, after that i will working multiple pacakge manager support

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
