### PR TITLE
docs(tooltip): decrease zIndex so it doesn't overlap other elements

### PR DESCRIPTION
**Pull request by jvzaniolo**
## 📝 Description

The floating Tooltip was overlapping the navbar and other elements on the home page.

I decreased its `z-index` to 39 because the navbar is `.z-40`

## ⛳️ Current behavior (updates)

https://github.com/nextui-org/nextui/assets/54036572/69685a81-88ee-48e8-9e24-9c677e77ffe2

## 🚀 New behavior

https://github.com/nextui-org/nextui/assets/54036572/5fe3bf4a-3925-4838-b89e-316a62a7f883

## 💣 Is this a breaking change (Yes/No):

No

### CODE REVIEW

**Comment by jguddas** [comment]
image

We should just reduce the z-index of the tooltip, so we don't have to fix this in a bunch of places.

**Comment by jrgarciadev** [comment]
Hey @jguddas it can be done by doing this:

https://github.com/nextui-org/nextui/issues/1409#issuecomment-1679621977

**Comment by jvzaniolo** [comment]
@jrgarciadev @jguddas I decreased the tooltip z-index as mentioned :)

**Review by jrgarciadev — APPROVED** [review]

**Comment by jrgarciadev** [comment]
Thank you! @jvzaniolo

**Pull request merged**
