### PR TITLE
fix(date-picker): filter out non-DOM props to prevent console errors

### LINKED ISSUE #2823: [BUG] - DatePicker props
### NextUI Version

2.3.5

### Describe the bug

All my props that I pass to the component work correctly, but if you open the calendar, you can see an error in the console for all my props.
Example:
`React does not recognize the placeholderValue prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase placeholdervalue instead. If you accidentally passed it from a parent component, remove it from the DOM element.`
`React does not recognize the hideTimeZone prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase hidetimezone instead. If you accidentally passed it from a parent component, remove it from the DOM element.`

Example code:

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Write component. For example:
 ```typescript
<DatePicker
  isRequired
  isReadOnly={disabled}
  label={'Activity date'}
  isInvalid={fieldState.invalid}
  errorMessage={fieldState.error?.message}
  hideTimeZone={true}
  placeholderValue={now(getLocalTimeZone())}
/>
```
2. Click to icon for open calendar
3. Open dev tools and see error

### Expected behavior

As a developer, I expected that there would be no errors in devtools

### Screenshots or Videos

_No response_

### Operating System Version

Windows

### Browser

Chrome

### PR DESCRIPTION
**Pull request by ryo-manba**
Closes #2823

## 📝 Description

This PR addresses console errors that appear when unrecognized props are passed to the DOM elements in the DatePicker. Props like `placeholderValue` and `hideTimeZone` are now handled to prevent them from being passed to the DOM.

### Test Steps

1. Display a DatePicker with the following setup:

```tsx
  return (
    <DatePicker
      isRequired
      hideTimeZone={true}
      label="Activity date"
      placeholderValue={now(getLocalTimeZone())}
    />
  );
};
```
2. Open the calendar and verify that no warnings are displayed.

### Before

https://github.com/nextui-org/nextui/assets/76232929/cc4a617c-bf1f-4e64-8e07-cf51f029ea24

### After

https://github.com/nextui-org/nextui/assets/76232929/80206116-36cd-4021-90b8-54651b66f33d

## ⛳️ Current behavior (updates)

Passing unrecognized props like `placeholderValue` and `hideTimeZone` to the DatePicker triggers console errors.

## 🚀 New behavior

Unrecognized props are now filtered out before rendering, preventing any console errors.

## 💣 Is this a breaking change (Yes/No):

No.

## Summary by CodeRabbit

- **Bug Fixes**
	- Improved error handling in the DatePicker component to prevent console errors related to inappropriate prop types.
- **Refactor**
	- Enhanced type declarations and function return types in DatePicker functionalities for better code clarity and reliability.
	- Updated value handling in DatePicker to ensure more robust and fault-tolerant input processing.
- **Tests**
	- Added new props and console spies for comprehensive testing coverage in the DatePicker component.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
Can we also have some tests in date picker to prevent this issue in the future?

**Comment by ryo-manba** [comment]
@wingkwong 
I've tightened type constraints in the useDatePicker hooks without using the as keyword.
This should statically prevent the problem in the future.

**Comment by wingkwong** [comment]
@ryo-manba maybe also check once in useCalendar

**Comment by ryo-manba** [comment]
@wingkwong 
Thanks for the comment. I added a test.

**Review by jrgarciadev — APPROVED** [review]
Thank. you! @ryo-manba

**Pull request merged**
