### PR TITLE
[BUG] - `disabled` prop of Loading Buttons in StoryBook restricts `color type` visibility.

### LINKED ISSUE #878: [BUG] - Duplicate `Spinner Button` in StoryBook
### Describe the bug

Duplicate `Spinner Button` in below `StoryBook` script, please go through below link.

(https://github.com/nextui-org/nextui/blob/main/packages/react/src/button/button.stories.tsx) - `Line 71 - 75`

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

please go through below link.

(https://github.com/nextui-org/nextui/blob/main/packages/react/src/button/button.stories.tsx) - `Line 71 - 75`

### Expected behavior

No Duplicate `Spinner Button` in below `StoryBook` script. 

image

_No response_

### Operating System Version

Windows 11 Pro

### Browser

Chrome

### PR DESCRIPTION
**Pull request by alphaxek**
Closes #878

## 📝 Description

This PR removes duplicate `Spinner Button` from `Button->Loading StoryBook`

## ⛳️ Current behavior (updates)

Duplicate `Spinner Button` in`Button->Loading StoryBook`

## 🚀 New behavior

No duplicate `Spinner Button` in`Button->Loading StoryBook`

## 📝 Additional Information
No Comments

### CODE REVIEW

**Comment by sun0day** [comment]
The loading story is better to show different type of loading button, I suggest remove the `disabled` prop of each loading button

image

**Comment by alphaxek** [comment]
Thank you @sun0day and @gauravkrp for your reviews.

**Comment by alphaxek** [comment]
HI @sun0day, still getting `First-time contributors need a maintainer to approve running workflows.`

**Review by gauravkrp — APPROVED** [review]

**Review by sun0day — APPROVED** [review]

**Comment by alphaxek** [comment]
Hi @sun0day, is it because of storybook deployment failure, o shall I do another PR.
It still says require approval

image

**Pull request closed without merging**
