### PR TITLE
fix: resolved rtl direction problems

### PR DESCRIPTION
**Pull request by jguddas**
## 📝 Description

The quality of v2 is incredible, I really had a hard time finding something to nitpick.

This resolves all the funkiness I could find when setting `dir="rtl"`.

For `pagination` I haven't yet found a solution, so I set if to `dir="ltr"`, so it does not look broken anymore.

## ⛳️ Current behavior (updates)

image

## 🚀 New behavior

image

## 💣 Is this a breaking change (Yes/No):

No changes for the end user nor the developer.

## 📝 Additional Information

> The total number of potential users is of course an overestimate, because it doesn't take into account literacy levels or competing scripts or usage trends. Nonetheless, at 2,305,048,719 it indicates that the actual number of potential users possibly runs past a billion.

[https://www.w3.org/International/questions/qa-scripts](https://www.w3.org/International/questions/qa-scripts#:~:text=The%20total%20number%20of%20potential%20users%20is%20of%20course%20an%20overestimate%2C%20because%20it%20doesn%27t%20take%20into%20account%20literacy%20levels%20or%20competing%20scripts%20or%20usage%20trends.%20Nonetheless%2C%20at%202%2C305%2C048%2C719%20it%20indicates%20that%20the%20actual%20number%20of%20potential%20users%20possibly%20runs%20past%20a%20billion.)

### CODE REVIEW

**Comment by sbc640964** [comment]
Waiting for the merge

**Comment by jguddas** [comment]
@jrgarciadev, can you take a look at this?

**Comment by jrgarciadev** [comment]
Great job @jguddas! 

We're planning on using the `i18n` locale given by `react-aria` to detect the user's language direction and integrate it into the NextUI provider's root. You can learn more about it [here](https://react-spectrum.adobe.com/react-aria/internationalization.html#example).

While it's a good starting point, The feature to support RTL on all components requires substantial time and effort on our part so we'll likely roll this out after the v2 release, so we can focus on our immediate commitments without any compromises.

Thanks for all your hard work!, I'll leave this PR open to merge it when we start working on RTL support. 

Keep pushing 🙌🏻

**Comment by jguddas** [comment]
> We're planning on using the `i18n` locale given by `react-aria` to detect the user's language direction and integrate it into the NextUI provider's root. You can learn more about it [here](https://react-spectrum.adobe.com/react-aria/internationalization.html#example).

Great minds think alike, I also have a PR for that one :D. https://github.com/nextui-org/nextui/pull/1145#issuecomment-1586162974

> Thanks for all your hard work!, I'll leave this PR open to merge it when we start working on RTL support.

This PR is in a mergable state, every component looks works now in RTL mode.

But I understand that you have to review/test this, and that takes time.

**Comment by jguddas** [comment]
Before this can be merged, the following steps need to be run.
- `cd packages/components/pagination`
- `pnpm install @react-aria/i18n --save`
- `git add --update ../../..`
- `git commit --message "deps: added @react-aria/i18n to @nextui-org/pagination"`
- `git push`

I have not done this for now to avoid merge conflict hell.

**Comment by sbc640964** [comment]
@jguddas, By the way, tailwind 3.3 lets you write more concisely.

For example:
```css
- "pl-3 rtl:pl-0 rtl:pr-3"
+ "ps-3"
```

**Comment by jrgarciadev** [comment]
Hey @jguddas please check this https://tailwindcss.com/blog/tailwindcss-v3-3#simplified-rtl-support-with-logical-properties

**Comment by meerns** [comment]
@jrgarciadev any update on this ?

**Comment by jguddas** [comment]
We should add RTL support by using the tailwind start and end helper @sbc640964 mentioned here https://github.com/nextui-org/nextui/pull/1143#issuecomment-1600111317.

And do so one component at a time.

Examples https://github.com/nextui-org/nextui/pulls?q=is%3Apr+is%3Aopen+RTL

List of known automatically detected issues: https://github.com/nextui-org/nextui/actions/runs/6371397569/job/17293304674?pr=1724

**Pull request closed without merging**
