### PR TITLE
refactor: improve dx for writing a docs component

### PR DESCRIPTION
**Pull request by Innei**
Closes # 

## 📝 Description

> Add a brief description

The component DX that writes docs now is very unfriendly and difficult to maintain.

Like this. What stringfiy code??

CleanShot 2024-03-18 at 9  39 42@2x

For now, I just refactor this and improve DX. And now we can write code in single tsx file, and import it.
CleanShot 2024-03-18 at 9  40 39@2x

And import it assert to raw.

```ts
import App from "./bordered-variant.raw.tsx?raw";

const react = {
  "/App.jsx": App,
};

export default {
  ...react,
};

```

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new way to import and use components in the documentation app, enhancing code readability and maintainability.
	- Added a new computed field in the `Doc` and `BlogPost` document types for improved functionality.
- **Documentation**
	- Updated the documentation app configuration to support new content types and improve the authoring experience.
- **Refactor**
	- Refactored accordion components to use a more efficient import method.
- **Chores**
	- Updated dependencies to ensure compatibility and security, including the addition of `esbuild-plugin-raw`.
- **Tests**
	- Ensured all new changes are compatible with existing configurations and types.

### CODE REVIEW

**Comment by ryo-manba** [comment]
@Innei 
Thanks for your PR!
Could you please resolve the conflicts so that we can proceed with the review?

**Comment by wingkwong** [comment]
after syncing latest canary branch, this PR no longer works. Therefore I made the following changes.

- switch from `contentlayer` to `contentlayer2` since `contentlayer` doesn't support node 20 and out of maintenance. (by the time this PR was made, we were still using node 16 / 18)
- bump docs related dependencies because of `contentlayer2`, e.g. rehype, remark, unified, unist-util-visit etc.
- bump ts version to v5 (ts-pattern requires that)
- fix module "*.tsx?raw" type and rename to avoid conflict with `@types`

After this PR is merged, I'll change the rest of the components.

**Review by ryo-manba — APPROVED** [review]
Looks good!
Thanks @Innei and @wingkwong.

**Comment by Innei** [comment]
Sorry, I haven't paid attention to this project for a long time and ignored these updates.

**Pull request merged**
