### PR TITLE
fix(navbar ): height overflow when h-full

### LINKED ISSUE #1694: [BUG] - Navbar positions
### NextUI Version

2.1.13

### Describe the bug

The navbar when used with position sticky takes space inside the page lets say if I use w-screen and h-screen although it is sticky it still takes space in the page which causes the page to become scrollable.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1.Use Navbar with position sticky (default behavior)
2.Make the page take 100vw and 100vh

### Expected behavior

Should not cause the page to become scrollable.

### Screenshots or Videos

_No response_

### Operating System Version

Linux

### Browser

Chrome

### PR DESCRIPTION
**Pull request by abhinandan-verma**
Closes #1694

## 📝 Description

Fixed the overflow of navbar height over main content 

## ⛳️ Current behavior (updates)

before-1
before-2

## 🚀 New behavior

after

## Summary by CodeRabbit

- **Bug Fixes**
	- Resolved an issue with the navbar height, preventing it from taking up excessive vertical space in full-height scenarios. 
	- Improved layout stability and usability for components using the updated theme.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
your current behaviour and new behaviour are using two different examples. please also state which story you are using for testing.

**Comment by abhinandan-verma** [comment]
@wingkwong  I have used  same example for both new ad prev behaviour, 
Its  story of Navbar `With Menu` ,  you can produce the bug just by adding `className="h-full"` to  `WithMenuTemplate `

Screenshot 2024-07-22 at 11 30 32 AM

**Comment by wingkwong** [comment]
1. why do you set `h-full` for that?
2. how does this PR solve the issue? The issue is saying the page is scrollable when setting the page 100vw and 100vh. The changes you made and the demo you showed are not quite related to the reported issue.

i would suggest to ask for user to provide the reproducible env first.

**Comment by abhinandan-verma** [comment]
@wingkwong  sir even the `100vh` and  `100vw` has same issue. 
I don't believe any user would like such a navbar covering the whole screen content


https://github.com/user-attachments/assets/92255a67-fa9d-4845-b3c8-838b66b1e5a3

**Comment by wingkwong** [comment]
can you share a sandbox instead? it looks different on my side. from the screenshot you showed in new behaviour, it also contains a scrollbar which is already not expected.

**Comment by abhinandan-verma** [comment]
@wingkwong  You can easily reproduce the bug using the NextUI Template and editing the `navbar.tsx`  like this 

```bash
 <NextUINavbar maxWidth="xl" position="sticky" >
```
to 

```bash
 <NextUINavbar maxWidth="xl" position="sticky" className="w-screen h-screen">
```

or simply in storybook

by changing this [line](https://github.com/nextui-org/nextui/blob/canary/packages/components/navbar/stories/navbar.stories.tsx#L103)

by. 
```zsh
   <Navbar {...args} parentRef={parentRef} classname="h-screen w-screen" >
```
then see the story

**Comment by wingkwong** [comment]
The issue is talking about the page being set to 100vw and 100vh, not the navbar itself. Setting full height & width screen to navbar doesn't make any sense.

**Comment by wingkwong** [comment]
Closing - not applicable

**Pull request closed without merging**
