### PR TITLE
fix(theme): color discrepancy in select

### LINKED ISSUE #3659: [BUG] - Font color in Bordered select is always gray
### NextUI Version

2.4.6

### Describe the bug

Just came to NextUI for a few days. I have a bordered select. I found out the font color is always gray no matter what `color props`
Screenshot 2024-08-16 at 2 40 47 PM

As you can see, it's still gray even I set the `color="primary"`. It makes the font color inconsistent since the font color in `Input` is black while the font color in `Select` is gray

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

```tsx
<Select
  name="role_id"
  label="Job Role"
  labelPlacement="outside"
  startContent={
      <UserCircleIcon className="w-4 h-4 text-default-400 pointer-events-none" />
  }
  variant="bordered"
  color='primary'
  placeholder="Select your role"
  onChange={(e) => setData('role_id', e.target.value)}
>
  {roles.map(role => (
      <SelectItem key={role}>
          {role}
      </SelectItem>
  ))}
</Select>
```

### Expected behavior

The color should be consistent or is there any way to change the color in Select?

### Screenshots or Videos

_No response_

### Operating System Version

Mac

### Browser

Chrome

### PR DESCRIPTION
**Pull request by macci001**
Closes #3659 

#### 📝 Description

> The PR fixes the color of the selected value and label in SELECT component.

#### ⛳️ Current behavior (updates)

* Bordered: When value is selected in *SELECT* component, color remains `text-foreground-500`
Screenshot 2024-08-16 at 2 26 13 PM
* Underline:  When value is selected in *SELECT* component, color remains `text-foreground-500`. Label does not change the color according to the `color` variant.
Screenshot 2024-08-16 at 2 25 59 PM
* Flat: Currently the bg-color becomes darker on hover
* Faded: Hover does not have any effect on bg-color

#### 🚀 New behavior
* Bordered: Color becomes `text-default-foreground` when value is selected.
Screenshot 2024-08-16 at 2 23 52 PM
* Underline:  Color becomes `text-default-foreground` when value is selected. Label color changes according to the `color` variant.
Screenshot 2024-08-16 at 2 23 52 PM
* Flat: bg-color lightens on hover.
* Faded: bg-color will darken on hover. 

#### Select component after all changes
Screenshot 2024-08-22 at 1 38 44 PM

> Changes are made to the `value` slot in Border and Underline variants.

## Summary by CodeRabbit

- **New Features**
	- Enhanced styling for the select component to improve visual feedback based on the selection state.
	- New color rule for the default state, adjusting text color when a value is present.

- **Bug Fixes**
	- Corrected the color of the selected value to align with design standards.
	- Resolved label color issues in the underlined state for improved clarity.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
please add a changeset since you've modified files under `packages/`

**Comment by wingkwong** [comment]
@macci001 please DM me at discord (same username)

**Comment by macci001** [comment]
@wingkwong applied the asked changes and updated the PR description.

**Review by wingkwong — APPROVED** [review]

**Comment by pompurin404** [comment]
> * Flat: Currently the bg-color becomes darker on hover

I'm sorry, but I personally think there is an issue with this change, as it causes the Select component and the Input component to behave inconsistently.

**Comment by wingkwong** [comment]
@macci001 please take a look

**Pull request merged**
