### PR TITLE
fix(select): use-multi-select typescript error

### PR DESCRIPTION
**Pull request by awesome-pro**
## 📝 Description
 Fixed the typescript `undefined`  error in use-multiselect hook

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## Summary by CodeRabbit

- **Improvements**
	- Enhanced type safety and clarity in the `useMultiSelect` function for better handling of selected keys.
	- Updated imports to utilize explicit type definitions, reducing potential type-related errors.

### CODE REVIEW

**Review by wingkwong — CHANGES_REQUESTED** [review]
1. please share a sandbox to demonstrate the issue
2. add a changeset

**Comment by abhinandan-verma** [comment]
@wingkwong  the issue is `eslint` `error TS2354` on these lines while project is open
1. [line 1](https://github.com/nextui-org/nextui/blob/canary/packages/hooks/use-aria-multiselect/src/use-multiselect.ts#L67)
2. [line 2](https://github.com/nextui-org/nextui/blob/canary/packages/hooks/use-aria-multiselect/src/use-multiselect.ts#L81)

do I need to add `changeset`

**Comment by wingkwong** [comment]
i don't see such error

**Comment by abhinandan-verma** [comment]
@wingkwong  kindly see here (vs code)

Screenshot 2024-07-30 at 2 46 20 PM

**Comment by abhinandan-verma** [comment]
but I am having this issue for a longer time, every time I open this file,
So I thought to remove it.

**Comment by wingkwong** [comment]
closing - this part may be modified when bumping RA version

**Pull request closed without merging**
