### PR TITLE
fix(link): deprecated onClick warning on using onPress

### LINKED ISSUE #3196: Got "onClick is deprecated, please use onPress" while no `onClick` is used
### Discussed in https://github.com/nextui-org/nextui/discussions/3193

<div type='discussions-op-text'>

<sup>Originally posted by **bllakcn** June  6, 2024</sup>
My first time using the `as` prop to render a `Link` component as a `Button`.
I see this in my console
`onClick is deprecated, please use onPress` from useLink.

Is there anything I did wrong on my side?
```tsx
<Button
  as={Link}
  color='primary'
  onPress={doSomething}
  href={/}
  >
  Go somewhere
</Button>
```

### PR DESCRIPTION
**Pull request by awesome-pro**
Closes #3196

## 📝 Description

 Fixed the console warning `onClick is deprecated, please use onPress`  on using `onPress` with `Button` as `Link`

> Add a brief description

## ⛳️ Current behavior (updates)

https://github.com/user-attachments/assets/0d5bdc9a-b9a4-410a-a43d-782e70ca80fe

## 🚀 New behavior

https://github.com/user-attachments/assets/7651d4cd-2d73-4a12-8590-1973fa3b5641

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved a warning related to deprecated functionality in the link component, enhancing stability and reliability.

- **New Features**
  - Updated the link component to utilize an improved accessibility hook, enhancing compatibility and user experience.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
we no longer use `@nextui-org/use-aria-link`. here's a few thing to check

- whether latest `@react-aria/link` would solve the issue
- if not, sync the diff back to `@nextui-org/use-aria-link`

**Comment by abhinandan-verma** [comment]
@wingkwong  sir updated `@react-aria/link` to the latest version, currently no new update.
Can you explain a bit what you meant in step 2

**Comment by wingkwong** [comment]
> updated @react-aria/link to the latest version, currently no new update available.

both statement are contradicted

> Can you explain a bit what you meant in step 2

This is not step 2. I mean if there is a new version of `@react-aria/link` and it doesn't work. Then sync the difference back to our custom package `@nextui-org/use-aria-link`.

**Comment by wingkwong** [comment]
Just checked myself. No new logic introduced in RA side. Good to use `@nextui-org/use-aria-link` back.

**Review by wingkwong — APPROVED** [review]

**Pull request merged**
