### PR TITLE
fix(calendar): apply inert attribute according to isHeaderExpanded

### PR DESCRIPTION
**Pull request by KumJungMin**
## 📝 Description

- (_In Firefox / develop mode_) when i open datePicker, the attribute value error is occurred

스크린샷 2024-05-27 오후 12 29 29

_error console_

스크린샷 2024-05-27 오후 12 21 24

<br/><br/>

- So I fixed to toggle inert attribute according to isHeaderExpanded
```js
{...{inert: isHeaderExpanded ? "" : undefined}}
```

## Summary by CodeRabbit

- **Refactor**
  - Improved the assignment of the `inert` attribute in the calendar components for better code clarity and maintainability.

### CODE REVIEW

**Comment by jrgarciadev** [comment]
@KumJungMin please add the changeset

**Comment by KumJungMin** [comment]
> @KumJungMin please add the changeset
thank you comment :)
i added changeset file ([cd3c622](https://github.com/nextui-org/nextui/pull/3087/commits/cd3c622670632dda2459e7e2ba2032c69d0981a6))

**Comment by wingkwong** [comment]
@KumJungMin can you double check if this issue is still reproducible in the current nextui documentation? I tired to use firebox to reproduce but i didn't see this error. Probably it could have been resolved in [this PR](https://github.com/nextui-org/nextui/pull/3054).

**Comment by KumJungMin** [comment]
> @KumJungMin can you double check if this issue is still reproducible in the current nextui documentation? I tired to use firebox to reproduce but i didn't see this error. Probably it could have been resolved in [this PR](https://github.com/nextui-org/nextui/pull/3054).

---

Oh! the issue was resolved :) thank you for check!

**Pull request closed without merging**
