### PR TITLE
fix(theme): make skeleton invisible after data loaded

### LINKED ISSUE #3214: [BUG] - Skeleton animation is superimposed on other elements
### NextUI Version

2.4.1

### Describe the bug

In the sandbox you can see how there are 2 skeleton components in which each one has a button, the 2 button of the skeleton works normally the poite but in the first one only 25% of the button has poiter because the 2 skeleton is superimposed on it.

### Your Example Website or App

https://codesandbox.io/p/devbox/nextui-template-w3j84m

### Steps to Reproduce the Bug or Issue

1. Place the mouse cursor on the first button.
2. Place the cursor on the second button

### Expected behavior

The isLoaded prop should hide the skeleton

### Screenshots or Videos

_No response_

### Operating System Version

Windows 11

### Browser

Chrome

### LINKED ISSUE #3670: [BUG] - Skeleton is overflowing with isLoaded=true
### NextUI Version

2.4.6

### Describe the bug

Using <Skeleton> with `isLoaded={true}` overflows the `::before` element on the left of the element.
 - Element on the left are thus getting covered by an invisible element and thus not interactive.
 - The animation flashes on the left of the element in cases where the element is not removed and readded (see video)

### Your Example Website or App

https://codesandbox.io/p/devbox/cranky-euclid-hjympl?workspaceId=6a536476-25bc-4d3c-9a8a-569f4ba3a731

### Steps to Reproduce the Bug or Issue

1. Click Hide Skeleton

### Expected behavior

Button A should be clickable 

### Screenshots or Videos

Button A is not clickable

Also a video of the overlay flashing (after reloading)

https://github.com/user-attachments/assets/f5274588-6d55-43ec-8472-c21af6999ec7

### Operating System Version

macOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by chirokas**
- Closes #3214
- Closes #3670

## ⛳️ Current behavior (updates)

> Please describe the current behavior that you are modifying

## 🚀 New behavior

> Please describe the behavior or changes this PR adds

## Summary by CodeRabbit

- **Bug Fixes**
  - Resolved issue where the skeleton loader remained visible after data was loaded.
  - Fixed overflow issue with the skeleton component to enhance UI rendering.

- **New Features**
  - Introduced new visibility properties and transition effects for the skeleton component to improve loading animations.

### CODE REVIEW

**Review by wingkwong — COMMENTED** [review]
can you double check if `transition-opacity-visibility` is required here? I couldn't see the styles applying when `disableAnimation` is `false`.

**Comment by chirokas** [comment]
@wingkwong :

I'd like the fade-in animation (Hide -> Show) to be smooth.

https://github.com/nextui-org/nextui/assets/157580465/57fac5e2-22cb-443b-ba6d-9ebd3b7b800e

**Review by wingkwong — APPROVED** [review]

**Comment by jrgarciadev** [comment]
@wingkwong I belive this can be fixed by using `z-[-1]` what do you think?

**Comment by LeakedDave** [comment]
Any way to use this fix in my project? Whenever isLoaded gets toggled, it renders weird bars behind the Skeleton when isLoaded gets set to true. Only happens when children are inside the skeleton. On Chrome

**Comment by wingkwong** [comment]
@chirokas can you also take a look at the animation flashing issue mentioned in #3670?

**Comment by u3u** [comment]
@wingkwong @jrgarciadev 
This modification has caused the regression of issues #1502 and #2677.

**Comment by u3u** [comment]
https://tailwindcss.com/docs/transition-duration#using-custom-values
Sorry, I made a mistake! After upgrading TailwindCSS, you need to set `transitionDuration` separately.

**Comment by wingkwong** [comment]
> This modification has caused the regression of issues #1502 and #2677.
> 
> https://github.com/nextui-org/nextui/blob/canary/packages/core/theme/src/utilities/transition.ts
> 
> https://github.com/nextui-org/nextui/commits/canary/packages/core/theme/src/utilities/transition.ts


Will check when I get access to my laptop later

**Comment by wingkwong** [comment]
No worries. Thanks for the update.

**Pull request merged**
