### PR TITLE
v2.2.0 🕹️

### LINKED ISSUE #172: New Component: Range-slider
Would love to see something like 1. & animatable like 2.
1. https://chakra-ui.com/docs/form/range-slider#customizing-the-slider
2. https://www.framer.com/components/slider/

### LINKED ISSUE #694: [Feature Request] Breadcrumbs
### Is your feature request related to a problem? Please describe.

Hi NextUI team, NextJS' page based routing lends itself to a hierarchical page structure. My app has lots of nested pages and I want to show users where they are in the hierarchy.

### Describe the solution you'd like

An easily configured UI element that can take router.query arguments from NextJS' router and show the hierarchical position to the user.

Ex. 

HomePage > Page > Subpage > Subsubpage

### Describe alternatives you've considered

NextJS has a [breadcrumbs package](https://www.npmjs.com/package/nextjs-breadcrumbs) on NPM and a workaround isn't too difficult so far, but a solution that has shares a common theme with NextUI would be great.

### Screenshots or Videos

_No response_

### LINKED ISSUE #888: [Feature Request] New Component Slider
### Is your feature request related to a problem? Please describe.

NextUI does not have a slider component.

### Describe the solution you'd like

Slider

### Describe alternatives you've considered

Slider

### Screenshots or Videos

_No response_

### LINKED ISSUE #1397: [Feature Request] Autocomplete possibility
### Is your feature request related to a problem? Please describe.

I'm looking for a component / example how to implement a autocomplete feature in NextUI. Something like the google search bar or a street finder.

### Describe the solution you'd like

The user has a text input field and as soon as they type, the app can send a request to the backend and render the recieved values in some sort of drop down field.

### Describe alternatives you've considered

MUI has such a mechanism for example: https://mui.com/joy-ui/react-autocomplete/
I'm also thinking about implementing this with a regular NextUI dropdown component but this seems hacky

### Screenshots or Videos

_No response_

### LINKED ISSUE #1534: [Feature Request] Autocomplete for Select/Text Input
### Is your feature request related to a problem? Please describe.

The current library offers a range of user interface components but lacks an Autocomplete feature for select or text input fields. In scenarios where we have a long list of options or free text entry with suggested inputs, the lack of autocomplete functionality leads to a less user-friendly experience.

### Describe the solution you'd like

An Autocomplete component that can be easily integrated with existing select and text input fields would be a welcome addition. This component should allow for:

Dynamic fetching of options as the user types
Customizable rendering of option items
Ability to work with controlled and uncontrolled form scenarios

### Describe alternatives you've considered

Currently, developers have to manually integrate third-party libraries for autocomplete features or build custom components from scratch. While these are valid alternatives, having a built-in solution would ensure better style and behavior consistency across the app.

### Screenshots or Videos

_No response_

### LINKED ISSUE #1650: [BUG] - Popover Blur and Opaque on mobile
### NextUI Version

2.1.13

### Describe the bug

When you touch the blur or opaque popover on mobile it is not working

### Your Example Website or App

https://nextui.org/docs/components/popover#backdrop

### Steps to Reproduce the Bug or Issue

1. Open DevTools and activate device emulation.
2. Choose a mobile device.
3. Click on either 'opaque' or 'blur'.

### Expected behavior

As mobile User, I should be able to see content.

### Screenshots or Videos

https://github.com/nextui-org/nextui/assets/48190882/e551c11a-55db-470d-a6e2-57233403ff2d

### Operating System Version

macOs, android

### Browser

Chrome

### LINKED ISSUE #1654: [Feature Request] Autocomplete
### Is your feature request related to a problem? Please describe.

Would be nice to have a autocomplete component like this one from MUI:

https://mui.com/material-ui/react-autocomplete/

### Describe the solution you'd like

I'd like to have a component for this as it is very hard to implement on your own with the existing components.

### Describe alternatives you've considered

Using MUI

### Screenshots or Videos

_No response_

### LINKED ISSUE #1670: [Feature Request] stepper and searchable select/autocomplete
### Is your feature request related to a problem? Please describe.

A searchable or autocomplete suitable for large data and a stepper useful for multi step form

### Describe the solution you'd like

The two components are in reference to mantineUI, behavior can be similar.

### Describe alternatives you've considered

Coming from mantineUI, those are only two components lacking 

### Screenshots or Videos

_No response_

### LINKED ISSUE #1691: [BUG] - Typescript error with DropdownItem
### NextUI Version

2.1.13

### Describe the bug

Hello,
I have a type issue when using the Dropdown component, this is the code triggering the ts error:

```
<DropdownMenu aria-label="Profile Actions" variant="flat">
    { menuItems.map((entry) => (
        <DropdownItem key={entry.link} showDivider={entry.divider}>
            {entry.name}
        </DropdownItem>
    ))}
    <DropdownItem key="custom">Test123</DropdownItem>
</DropdownMenu>
```

The error is: `Type 'Element[]' is not assignable to type 'CollectionElement<object>'`.
The code runs fine and the result is as expected, that is a list of DropdownItems followed by the non-iterated "Test123" item, but the error (that I couldn't suppress) prevents me from building the app for production.

If I wrap it with a fragment `<></>`, which makes the TS error disappear, this time the error is at runtime and becomes `TypeError: Cannot convert a Symbol value to a string`.

Any idea on how to make it work? I have custom element at the bottom of this dropdown, that doesn't match the structure of the iterated elements.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

I'm using Typescript 5.1.6 and NextJS 13.4.13

### Expected behavior

There should be either no runtime or linter errors.

### Screenshots or Videos

_No response_

### Operating System Version

Windows with Linux Subsystem 2.0 (Debian LTS)

### Browser

Chrome

### LINKED ISSUE #1737: [BUG] Popover Blur and Opaque on mobile
Yes, but... it is not working on mobile. @jrgarciadev so that is not a solution at all.

https://github.com/nextui-org/nextui/assets/48190882/66ec6d1b-39a0-49f6-8f42-f35bdfd6a0c8

_Originally posted by @isaacismaelx14 in https://github.com/nextui-org/nextui/issues/1650#issuecomment-1747361588_

### LINKED ISSUE #1761: [BUG] - SelectItem & ListBoxItem extendVariants -> Error: type.getCollectionNode is not a function
### NextUI Version

^2.1.13

### Describe the bug

Bug is already pretty well described in Discord: https://discord.com/channels/856545348885676062/1161994818424156211

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. extendVariants of SelectItem:

```
import {
  Select as NextUISelect,
  SelectItem as NextUISelectItem,
  SelectProps as NextUISelectProps,
  SelectItemProps as NextUISelectItemProps,
  extendVariants,
} from "@nextui-org/react"

interface SelectItemProps extends NextUISelectItemProps {
  variantType?: "primary"
}

const SelectItemComponent = extendVariants(NextUISelectItem, {
  variants: {
    variantType: {
      primary: {
        description: '',
        base: '',
        title: '',
        wrapper: '',
        selectedIcon: '',
        shortcut: '',
      }
    }
  },
  defaultVariants: {
    variantType: "primary",
  }
})

export function SelectItem(props:SelectItemProps) {
  return (
    <SelectItemComponent { ...props } />
  )
}
```

There will be error: 
`Error: type.getCollectionNode is not a function`

### Expected behavior

Should work just like in button, pagination etc. components.

### Screenshots or Videos

_No response_

### Operating System Version

Windows 11

### Browser

Chrome

### LINKED ISSUE #1780: [BUG] - Components/Chips
### NextUI Version

2.1.13

### Describe the bug

Popover component can not be opened with `backdrop` property equals `blur` or `opaque` in device mode

### Your Example Website or App

https://nextui.org/docs/components/popover#backdrop

### Steps to Reproduce the Bug or Issue

1. Open developer tools
2. Toggle device toolbar 
3. Click on example with `backdrop` = `blur` or `opaque`

### Expected behavior

Popover should be open on click or tap

### Screenshots or Videos

Untitled

### Operating System Version

macOS

### Browser

Chrome

### LINKED ISSUE #1804: [Feature Request] Where is the slider?
### Is your feature request related to a problem? Please describe.

I am about to convert my application UI to your UI library as part of a design rebrand. 

I'm making sure that everything is compatible, and one component that is not listed in your documentation can be traced in your codebase. That is the `slider` component. 

I see in a PR that it can be found at `packages/components/slider/src/slider.tsx` https://github.com/nextui-org/nextui/pull/1693/files but is not found in your document components https://nextui.org/docs/components.

Are there other components that are available but not listed?

On a related note, I also notice that there are several components missing from the Figma file. Namely the `dropdown` and `select`. 

### Describe the solution you'd like

Could I please request that all forms of documentation and design file be updated promptly? 

### Describe alternatives you've considered

This would require digging into the codebase and then the designer having to go through a much more lengthly process to deliver the designed UI assets. 

### Screenshots or Videos

Screen Shot 2023-10-24 at 9 14 27 AM
Screen Shot 2023-10-24 at 9 14 35 AM
Screen Shot 2023-10-24 at 9 14 41 AM

### LINKED ISSUE #1822: [Feature Request][Dropdowns] PreserveDefaultKeypressEvent flag
### Is your feature request related to a problem? Please describe.

Hello.

By default, pressing the ENTER key and/or the SPACE key should dispatch a `click` event for some tagnames (especially on `<button>` and `<a>`).

For example, the expected default behaviour on a `<button>` should be :
- SPACE: `click`
- ENTER: `click`

And on a `<a>`:
- SPACE: _nothing_
- ENTER: `click`

When we're working on vanilla code, this is the behaviour of web browsers. It is provided for-free, and no more custom logic/magic is required.

Unfortunately, this behaviour is not preserved on _Dropdown_ items. I could do some "magic" by implementing custom functions, as suggested in the documentation. But I think that's a pain we should be able to avoid.

At the moment, if I press the SPACE key or the ENTER key when the focus is on an `<a>` or a `<button>` within a dropdown menu, it just closes, and I don't think it is the desirable behaviour in this scenario.

For example, if I go on this demo: https://next-ui-toggler-bug-demo.vercel.app/
And then click on the "Patch Notes" dropdown menu trigger button,
And then press the "Tab" (or Up/Down) key to move the focus on "Dashboard" | "Discord Bot",
And then press Enter,
The dropdown just closes.

I would have liked this to reproduce the expected default behaviour: a click, and therefore a redirect to the corresponding page.

### Describe the solution you'd like

I would like to have a `PreserveDefaultKeypressEvent` flag for the dropdowns items.
I _think_ this bug is because of some `preventDefault` calls, which should be optional.

### Describe alternatives you've considered

Implementing by hand the dispatch event... Really annoying.

### Screenshots or Videos

_No response_

### Code
:arrow_right: https://github.com/gustaveWPM/next-ui-toggler-bug-demo/blob/main/src/components/layouts/navbar/NavbarDropdown.tsx

**Note**: a more recent implementation of this (respecting some ARIA concerns) could be find there:
:arrow_right: https://github.com/gustaveWPM/dashboard_rtm/blob/main/src/components/layouts/navbar/NavbarDropdown.tsx

### LINKED ISSUE #1837: [BUG] - Input and Select have different label colors
### NextUI Version

2.1.13

### Describe the bug

By default the components `Input` and `Select` have different text colors.

Input: `foreground-600`
Select: `foreground-500`

I noticed this when using both components next to another in a form, which would be a very common use case.

Further to that I had trouble easily changing the Select <label> color and needed to use CSS modules to do it.

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

Use default `Input` and default `Select` components.

### Expected behavior

Use a consistent color shade across both components.

I would personally suggest `foreground-600`.

### Screenshots or Videos

image

### Operating System Version

MacOS

### Browser

Chrome

### PR DESCRIPTION
**Pull request by jrgarciadev**
Closes #172 
Closes #886 
Closes #888  
Closes #1685 
Closes #694
Closes #1780 
Closes #1737 
Closes #1650 
Closes #1804 
Closes #1822
Closes #760 
Closes #1670 
Closes #1654 
Closes #1534 
Closes #1397 
Closes #1650 
Closes #1691
Closes #1837 
Closes #1761

## 📝 Description

- New component added: Slider #1686 
- New component added: Breadcrumbs #1794 
- New component: Single selection Autocomplete based on [useComboBox](https://react-spectrum.adobe.com/react-aria/useComboBox.html#usecombobox) and [useComboBoxState](https://react-spectrum.adobe.com/react-stately/useComboBoxState.html#usecomboboxstate)
- React Aria [Client side router](https://react-spectrum.adobe.com/react-aria/routing.html) support added, this allows components such as Link, Tabs, Listbox and Dropdown items to be rendered as links and navigate using the proper navigation function for each framework. #1764 
- RTL Support added to Accordion. #1725 
- RTL Support added to Avatar & AvatarGroup components #1727 
- RTL Support added to ButtonGroup #1726  
- Spacing units changed from `px` to `rem` this improves the mobile components' sizes #1688
- Tabs/Tab new prop added `shouldSelectOnPressUp` which is enabled by default `true`, this prop defines whether the tabs selection should occur on press up instead of press down. #1688
- Chip font size changed to `text-tiny` on `sm` size. #1688
- Button with only the icon now displays only the spinner during loading #1800 
- Popover open state fixed for blur/opaque backdrops #1812
- The ScrollShadow API has been enhanced with new features. Users can now manage the `visibility` of shadows using the `visibility` and `onVisibilityChange` props.  #1819
- `emptyContent` property added to Listbox/Menu/Dropdown
- `topContent` and `bottomContent` properties added to Listbox/Menu/Dropdown
- `baseRef` added to Input, it allows to control the input's parent element ref
- `tailwind-variants` upgraded to `v0.1.18` it includes slot variants control
- Custom `usePress` implemented to fix the corner press issue, opened a PR and Issue on react-aria project https://github.com/adobe/react-spectrum/pull/5291
- Custom `usePress` implemented across all NextUI interactive components
- Input & Select label animations & position improved
- react-aria packages and framer-motion upgraded
- Generic items typescript support added to `Menu` and `DropdownMenu` #1691 
- Popover animation improved
- Package dependencies were modified to not include the ones already installed through either global or individual installations. This reduces the individual package bundle size. #1848 
- Input outline removed on focus-visible
- ButtonGroup radius prop fixed
- `isActive` prop added to `NavbarMenuItem`
- Pagination custom-items example fixed, key prop added
- Collection Items are now supported by `extendVariants` function #1761  
- Transition added to menu/listbox items 
- `disableAutosize` prop added to Textarea, this disable the auto resize.
- Textarea styles fixed  
- Textarea height style animated 
- `hoverOpacity` key added to themes object in the plugin
- Button hover effect added 

### Breaking Changes

- Popover API changed to improve the arrow implementation, arrow is now a pseudo-element, which allows the popover to also move the arrow altogether, this change impacts the Popover, Tooltip and Select implementations.

Popover changes:

```diff
  <Popover
      showArrow
      backdrop="opaque"
      placement="right"
      classNames={{
-        base: "py-3 px-4 border border-default-200 bg-gradient-to-br from-white to-default-300 dark:from-default-100 dark:to-default-50",
-        arrow: "bg-default-200",
+        base: [
+          // the "before" pseudo element is now the popover' arrow
+          "before:bg-default-200"
+        ],
+        content: [ // now we need to use the "content" slot to actually modify the popover' content styles
+          "py-3 px-4 border border-default-200",
+          "bg-gradient-to-br from-white to-default-300",
+          "dark:from-default-100 dark:to-default-50",
        ],
      }}
    >
      <PopoverTrigger>
        <Button>Open Popover</Button>
      </PopoverTrigger>
      <PopoverContent>
        {(titleProps) => (
          <div className="px-1 py-2">
            <h3 className="text-small font-bold" {...titleProps}>
              Popover Content
            </h3>
            <div className="text-tiny">This is the popover content</div>
          </div>
        )}
      </PopoverContent>
  </Popover>
```

Tooltip changes:

```diff
 <Tooltip
      showArrow
      placement="right"
      content="I am a tooltip"
      classNames={{
-        base: "py-2 px-4 shadow-xl text-black bg-gradient-to-br from-white to-neutral-400",
-        arrow: "bg-neutral-400 dark:bg-white",
+        base: [
+          // the "before" pseudo element is now the popover' arrow
+          "before:bg-neutral-400 dark:before:bg-white",
+        ],
+        content: [ // now we need to use the "content" slot to actually modify the popover' content styles
+          "py-2 px-4 shadow-xl",
+          "text-black bg-gradient-to-br from-white to-neutral-400",
+        ],
      }}
    >
      <Button variant="flat">Hover me</Button>
</Tooltip>
```

Select changes:

```diff
 <Select
      items={users}
      label="Assigned to"
      className="max-w-xs"
      variant="bordered"
      classNames={{
        label: "group-data-[filled=true]:-translate-y-5",
        trigger: "min-h-unit-16",
        listboxWrapper: "max-h-[400px]",
      }}
      listboxProps={{
        itemClasses: {
          base: [
            "rounded-md",
            "text-default-500",
            "transition-opacity",
            "data-[hover=true]:text-foreground",
            "data-[hover=true]:bg-default-100",
            "dark:data-[hover=true]:bg-default-50",
            "data-[selectable=true]:focus:bg-default-50",
            "data-[pressed=true]:opacity-70",
            "data-[focus-visible=true]:ring-default-500",
          ],
        },
      }}
      popoverProps={{
        classNames: {
-          base: "p-0 border-small border-divider bg-background",
-          arrow: "bg-default-200",
+          base: "before:bg-default-200", // the before pseudo element controls the popover's arrow
+          content: "p-0 border-small border-divider bg-background", // now instead of the "base" slot we use the "content" slot
        },
      }}
      renderValue={(items) => {
        return items.map((item) => (
          <div key={item.key} className="flex items-center gap-2">
            <Avatar
              alt={item.data.name}
              className="flex-shrink-0"
              size="sm"
              src={item.data.avatar}
            />
            <div className="flex flex-col">
              <span>{item.data.name}</span>
              <span className="text-default-500 text-tiny">({item.data.email})</span>
            </div>
          </div>
        ));
      }}
    >
      {(user) => (
        <SelectItem key={user.id} textValue={user.name}>
          <div className="flex gap-2 items-center">
            <Avatar alt={user.name} className="flex-shrink-0" size="sm" src={user.avatar} />
            <div className="flex flex-col">
              <span className="text-small">{user.name}</span>
              <span className="text-tiny text-default-400">{user.email}</span>
            </div>
          </div>
        </SelectItem>
      )}
    </Select>
  );
}`;
```

Dropdown Changes

```diff
    <Dropdown
      showArrow
      classNames={{
-        base: "py-1 px-1 border border-default-200 bg-gradient-to-br from-white to-default-200 dark:from-default-50 dark:to-black",
-        arrow: "bg-default-200",
+        content: "py-1 px-1 border border-default-200 bg-gradient-to-br from-white to-default-200 dark:from-default-50 dark:to-black",  // now instead of the "base" slot we use the "content" 
+        base: "before:bg-default-200",  // the before pseudo element controls the popover's arrow
      }}
    >
```

### CODE REVIEW

**Comment by qWici** [comment]
@jrgarciadev can you tell me when the release of this version is planned?

**Comment by sayem314** [comment]
Any ETA for release? Need range slider by next week or must go with 3rd party lib by then.

**Comment by toxsick** [comment]
Hey @jrgarciadev, the new Autocomplete component looks awesome, but is there any chance we can have something like `renderValue` of the [Select](https://nextui.org/docs/components/select#custom-render-value) to render a custom selected values?

Thanks for the awesome work!

**Comment by jrgarciadev** [comment]
> Hey @jrgarciadev, the new Autocomplete component looks awesome, but is there any chance we can have something like `renderValue` of the [Select](https://nextui.org/docs/components/select#custom-render-value) to render a custom selected values?
> 
> Thanks for the awesome work!

Hey @toxsick thanks!, we plan to add custom render value support later, once we include the `multiple` selection mode

**Pull request merged**
