### PR TITLE
fix: isReadOnly in Autocomplete

### LINKED ISSUE #2420: [BUG] - AutoComplete ListBox still opening while isReadOnly set to true
### NextUI Version

2.2.9

### Describe the bug

ListBox still show up even isReadOnly set to true

### Your Example Website or App

_No response_

### Steps to Reproduce the Bug or Issue

1. Import Autocomplete component
2. Set isReadOnly to true

### Expected behavior

ListBox not popped out

### Screenshots or Videos

_No response_

### Operating System Version

Windows 10

### Browser

Chrome

### PR DESCRIPTION
**Pull request by wingkwong**
Closes #2420

## 📝 Description

- revised the isReadOnly logic in Autocomplete
- created `isReadOnly` example in storybook

## ⛳️ Current behavior (updates)

when `isReadOnly` is set, users 
- cannot edit the input
- can open the listbox
- can select the menu option

## 🚀 New behavior

when `isReadOnly` is set, users 
- cannot edit the input
- can open the listbox
- cannot select the menu option

image

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

When someone prefer to not open the listbox, then they should use `isDisabled` instead.

### CODE REVIEW

**Comment by jrgarciadev** [comment]
@wingkwong please remove the clear "X" button 

CleanShot 2024-03-05 at 09 55 17

**Comment by wingkwong** [comment]
@jrgarciadev just added.

image

**Comment by jrgarciadev** [comment]
> @jrgarciadev just added.
> 
> 
> 
> image
> 
> 

@wingkwong i mean if the isReadOnly is **true** we should no display the clear button

**Review by jrgarciadev — APPROVED** [review]
Thank you! @wingkwong

**Pull request merged**
