### PR TITLE
refactor(docs): revise code block

### PR DESCRIPTION
**Pull request by wingkwong**
Closes # 

## 📝 Description

- apply fold logic for the upcoming dx change (js will be merged into the main tsx / jsx so by default they should be folded)

## Release Notes

- **New Features**
	- Enhanced `Codeblock` component with improved code highlighting and rendering for different languages, including support for "diff" languages.
	- Introduced a new helper function for transforming tokens into a structured folder format.
	- Added new CSS classes to improve styling and layout for code components.

- **Bug Fixes**
	- Fixed issues with line number rendering and token display for copyable elements.

- **Style**
	- Updated global styles for `<pre>` elements and added new styles for interactive elements to enhance user experience.
	- Improved styles for the `.sp-editor` and related classes to ensure better layout and responsiveness.

### CODE REVIEW

**Review by ryo-manba — COMMENTED** [review]
Could you please provide a more detailed explanation in the PR about why this change is necessary and what it accomplishes? If there are any related issues or PRs, please link to them as well.

**Comment by wingkwong** [comment]
Some examples may import other code such as data.js, logo.tsx and etc. Currently it displays in different tabs. For example, `data.js` in https://nextui.org/docs/components/autocomplete#label-placements. With the new raw approach, you cannot import that in raw (from users perspective, the code should be ready to use by copying and pasting). Hence I put all the code together in the one single file App.jsx. In this case, users can just copy one file instead of setting up one by one. This is also a future plan for NextUI Pro as well. Since putting all the code together would make the code block longer, hence this PR introduces a collapsible code block, similar to nextui pro one, so that users can only focus on the main logic and expand other code if necessary.

**Comment by jrgarciadev** [comment]
@wingkwong would be great to refactor the examples code to have everything in a single tab

e.g. move `animals` array to the main `App` file

CleanShot 2024-11-04 at 18 28 42
CleanShot 2024-11-04 at 18 28 39

**Comment by wingkwong** [comment]
@jrgarciadev yes. actually it's already done in another PRs (See PR3934, 3951, 3960 ..etc). I made it separately for easy review. And this will merge to `refactor/overall-dx` first.

**Comment by jrgarciadev** [comment]
@wingkwong merged, please change other PRs (ready) from draft to ready to review

**Pull request merged**
