### PR TITLE
feat: added drawer component

### PR DESCRIPTION
**Pull request by 1111mp**
## 📝 Description
Added Drawer component. 

Learned about some user feature requests from [#2134 [Feature Request] Some Components Feature Suggestions](https://github.com/nextui-org/nextui/issues/2134), so I started to implement them from the simplest components (Because it can almost reuse Modal’s design and code).

- Closes: #2620
- Closes: #2376

## ⛳️ Current behavior (updates)

There is currently no support for the Drawer component.

## 🚀 New behavior

We can have the Drawer component.

## 💣 Is this a breaking change (Yes/No):

No. Supports the new Drawer component, which will not have any impact on other components.

## 📝 Additional Information

Screenshot 2024-01-10 at 18 26 54

There is currently some work yet to be completed, such as Drawer documentation and usage examples. Because I don’t know whether such code complies with the specifications of the warehouse, I initiated a PR in advance to confirm this. If all goes well I will continue with the rest of the work.

Feel free to point out my questions at any time. Of course, if you already have Drawer-related implementation plans or other questions, please let me know and I will close this PR. Thank you.

**This is a continuation of the previous [PR #2202](https://github.com/nextui-org/nextui/pull/2202).**

> I have read the [contributing guidelines](https://github.com/nextui-org/nextui/blob/921746f284668a303997d1f3b2fd4b825a2bb360/CONTRIBUTING.md) and [code of conduct](https://github.com/nextui-org/nextui/blob/921746f284668a303997d1f3b2fd4b825a2bb360/CODE_OF_CONDUCT.md) document.

### CODE REVIEW

**Comment by samuelbohl** [comment]
any updates on this?

**Comment by Mingyang-Li** [comment]
Component looks great 🤩

**Comment by jenslys** [comment]
any updates on this?

**Comment by ohIcee** [comment]
Any updates?

**Comment by wingkwong** [comment]
@1111mp can you ping me at [discord](https://discordapp.com/users/495466997304262658)?

**Comment by jrgarciadev** [comment]
Hey @1111mp thanks for your contribution, we will handle this internally here https://github.com/nextui-org/nextui/pull/3986

**Pull request closed without merging**
