### PR TITLE
feat(file-upload)

### LINKED ISSUE #3772: File Upload
### Discussed in https://github.com/nextui-org/nextui/discussions/1814

<div type='discussions-op-text'>

<sup>Originally posted by **scaki** October 21, 2023</sup>
### Is your feature request related to a problem? Please describe.

In today's online world, images, photos, avatars, text files are very important. It's a pity that the next ui library, which I love and enjoy using, doesn't have a file upload component. I hope it comes as soon as possible.

### Describe the solution you'd like

- Ability to select the desired file format
- Ability to upload single or multiple files

### Describe alternatives you've considered

[Ant Design Upload](https://ant.design/components/upload)

### Screenshots or Videos

_No response_</div>

### PR DESCRIPTION
**Pull request by Arian94**
Closes #3772,

## 📝 Description

> This will add the new long-awaited component called "File Upload".

## 🚀 New behavior

> This adds a customizable and flexible component to upload files. It constitutes three sections:
**Top Bar**: It is to display information regarding number of allowed files, file sizes etc.
**Items**: A container for the files a user has selected from his/her device.
**Buttons**: A container for the buttons such as the browse, add or reset button etc.

Developers are allowed to customize all three sections. There are many props for modifications and/or using customizable parts in these sections.

## 💣 Is this a breaking change (Yes/No):

No

## Summary by CodeRabbit

- **New Features**
	- Introduced a new "File Upload" component, allowing users to upload multiple files with customizable buttons.
	- Added new routes in the documentation for "File Upload" and several updated components.
	- Comprehensive documentation for the File Upload component, including installation instructions and usage examples.

- **Bug Fixes**
	- Updated sitemap to reflect new URLs and modifications for better navigation.

- **Documentation**
	- New README file for the `@nextui-org/file-upload` package detailing functionality and installation.
	- Added Storybook stories for the File Upload component to showcase various configurations.

- **Tests**
	- Implemented unit tests for the File Upload component to ensure functionality and behavior under different conditions.

### CODE REVIEW

**Comment by Arian94** [comment]
@wingkwong pls have a look.

**Review by wingkwong — COMMENTED** [review]
1. please add the documentation as well
2. please cover all the test cases
3. please cover all the cases in storybook

**Review by wingkwong — CHANGES_REQUESTED** [review]
please check all the coderabbitai conversations. mark resolved if completed.

**Comment by Arian94** [comment]
> please check all the coderabbitai conversations. mark resolved if completed.

I can't merge the newest updates from the canary branch. It stocks at prettifying **/*.css files.
Please assign this to someone else as I cannot continue working on it. It's got too lengthy.

**Pull request closed without merging**
