### PR TITLE
fix(input): sync ref value to internal value

### LINKED ISSUE #3024: [BUG] - Input component unresponsive to updates to value via `ref`
### NextUI Version

2.3.6

### Describe the bug

When modifying an input's value via its `ref` (i.e. how `react-hook-form` passes updates to components when the imperative `setValue` function is used), the input doesn't respond to the change.

I guess that RHF does something like `ref.current.value = "new value"`, so I have also provided an example in the StackBlitz project.

Without digging into the internals of the NextUI component, I'm guessing it creates a controlled input, making it incompatible with an uncontrolled form library.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-vnrckd?file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/vitejs-vite-vnrckd?file=src%2FApp.tsx
2. Observe the value in input and the printed value above and below the button.
3. Click the button.
4. Observe the printed value updates but the input value remains unchanged.
5. (Change the input value to observe the original value restored)the 

### Expected behavior

I expect the value of the input to change to track the form state.

### Screenshots or Videos

_No response_

### Operating System Version

Linux

### Browser

Chrome

### LINKED ISSUE #3436: [BUG] - Setting ref value (ie. uncontrolled) not supported by NextUI components
### NextUI Version

2.4.2

### Describe the bug

I create a ref via useRef and assign it to a component, such as the Autocomplete or Input elements, and while I can get the value just fine, assigning a new value results it in appearing temporarily in the component, but as soon as you mouse over the component it seems to redraw itself and the newly assigned value immediately disappears.

### Your Example Website or App

[Live Example](https://codesandbox.io/p/sandbox/nextui-numeric-input-validation-forked-9s6rg2?file=%2Fpackage.json%3A12%2C27)

### Steps to Reproduce the Bug or Issue

1) create a ref via useRef
2) assign ref to component (eg. Autocomplete or Input)
3) run the following code in a button click: ref.current!.value = 'new value'
4) observe 'new value' appear in the component, but when you mouse over or do anything that triggers a redraw (not react re-render, that's different)  then 'new value' disappears.

### Expected behavior

I expect the value assigned via the ref to persist, as it does in fact do with a regular html element such as the good old fashioned input element.

### Screenshots or Videos

_No response_

### Operating System Version

Windows 11

### Browser

Chrome

### LINKED ISSUE #3678: [BUG] - NextUI Input Field Value Disappears on Mouse Hover When Using React Hook Form
### NextUI Version

2.4.6

### Describe the bug

When using NextUI's Input component with React Hook Form, the input field value disappears upon mouse hover after setting the value programmatically with setValue.

### Your Example Website or App

https://github.com/iGmainC/nextui-bug

### Steps to Reproduce the Bug or Issue

Create a React component using Next.js, NextUI, and React Hook Form.
Set up a simple form with two input fields: name and password.
Add a button that, when clicked, sets the name field value to "root" using React Hook Form's setValue method.
Hover over the input field after clicking the button.

### Expected behavior

The input field should retain the value "root" when hovering over it.

### Screenshots or Videos

https://github.com/user-attachments/assets/494bc916-c69c-4a07-bcb9-71e8fa314449

### Operating System Version

linux

### Browser

Chrome

### PR DESCRIPTION
**Pull request by AnthonyPaulO**
Closes #3024
Closes #3436
Closes #3678

## 📝 Description

Fixed issue where setting the ref value doesn't sync the internal state, causing ref value changes not to persist and reverting back to the internal (state) value.

## ⛳️ Current behavior (updates)

Ref value changes do not persist as they do not update the internal (state) value.

## 🚀 New behavior

Ref value changes will now update the internal (state) value.

## 💣 Is this a breaking change (Yes/No):

No

## 📝 Additional Information

Video of fix:
https://github.com/user-attachments/assets/1406b00f-7c5f-42ee-9f3e-37a3a0fb9f78

## Summary by CodeRabbit

- **New Features**
	- Enhanced input component to synchronize its internal state with reference values, improving real-time data binding and responsiveness.

- **Bug Fixes**
	- Added a test case to ensure that changes to the reference value are accurately reflected in the input component’s internal state.

- **Refactor**
	- Improved the `useInput` hook for better control and handling of the input element's internal reference, increasing its flexibility and usability.

### CODE REVIEW

**Comment by AnthonyPaulO** [comment]
@jrgarciadev When you have a chance, would you review this? I'd love to see this in the next release.

**Review by wingkwong — APPROVED** [review]

**Comment by chirokas** [comment]
@wingkwong
https://github.com/user-attachments/assets/e6ff7bee-d9b1-4498-8c74-e127a8c315e3

**Comment by wingkwong** [comment]
@chirokas can u DM me at Discord (same username)?

**Comment by wingkwong** [comment]
@chirokas can u help take a look at this issue?

**Pull request merged**
